### ISSUE TITLE
Maximum size of the data

### ISSUE THREAD

**Issue by flefeb** [Artelnics/OpenNN#10]
Hi
I try to train a multilayer perceptron network with 1 one hidden layer. The number of neurons is 256 in the input layer, 25 in the hidden and 2 in the output. 
The perform_training function crashes in the dot function (levenberg_marquardt_algorithm.cpp) :
      JacobianT_dot_Jacobian = terms_Jacobian.calculate_transpose().dot(terms_Jacobian);
because it tries to allocate a vector of 6477*6477 values (6477 is the parameters_number, roughly the total number of connexions in the network).
My question is : is it possible to train a network with 256 inputs using openNN ? If yes, how should the parameters be settled to avoid this crash ?
Thank you

**Comment by FernandoGomezP** [comment]
The problem is the memory size of your computer. You can try the Quasi-Newton method, this one needs less memory and it is faster for a problem like yours

**Comment by flefeb** [comment]
Thank you for your answer.

My computer is 16Go RAM, I suppose it should be enough.  I tried on 
another computer but got the same problem, even using the quasi-newton 
method.


Le 06/06/2016 à 18:59, FernandoGomezP a écrit :
>
> The problem is the memory size of your computer. You can try the 
> Quasi-Newton method, this one needs less memory and it is faster for a 
> problem like yours
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Artelnics/OpenNN/issues/10#issuecomment-224020356>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AS3P1MsQsRPU7PDkKSOpGmoWXTQAcNIHks5qJFIAgaJpZM4Iu-dP>.
>

-- 
Françoise LEFEBVRE
IMNC (Imagerie et Modélisation en Neurobiologie et Cancérologie)
Campus d'Orsay - Bât 440
91405 ORSAY Cedex
01 69 15 51 87

**Comment by FernandoGomezP** [comment]
It is enough, we have loaded data sets with greater number of variables, maybe the problem is the number of instances. OpenNN loads the entire data set and it should not let memory for the elements of the training. 

What is the size of the data file? OpenNN has been tested with a computer with the same RAM, and we were able to load a data file of 3Gb.

**Comment by flefeb** [comment]
The output is a 2D position. For the tests, I used only 4 different 
positions and 40 samples of 256 inputs each per position.


Le 09/06/2016 à 13:54, FernandoGomezP a écrit :
>
> It is enough, we have loaded data sets with greater number of 
> variables, maybe the problem is the number of instances. OpenNN loads 
> the entire data set and it should not let memory for the elements of 
> the training.
>
> What is the size of the data file? OpenNN has been tested with a 
> computer with the same RAM, and we were able to load a data file of 3Gb.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Artelnics/OpenNN/issues/10#issuecomment-224873352>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AS3P1M550DvqpK4DRKTYRj3tDfe6i1s1ks5qJ_71gaJpZM4Iu-dP>.
>

-- 
Françoise LEFEBVRE
IMNC (Imagerie et Modélisation en Neurobiologie et Cancérologie)
Campus d'Orsay - Bât 440
91405 ORSAY Cedex
01 69 15 51 87

**Comment by FernandoGomezP** [comment]
It is a simple data set and OpenNN should load it. If you want send me that data set and we will test it in our computer. My mail is fernandogomez@artelnics.com

**Comment by flefeb** [comment]
I tried on another computer and the learning step is OK despite some 
error messages in debug mode. I continue using the other computer and I  
will ask you again if I hit other troubles

Thank you


Le 09/06/2016 à 13:54, FernandoGomezP a écrit :
>
> It is enough, we have loaded data sets with greater number of 
> variables, maybe the problem is the number of instances. OpenNN loads 
> the entire data set and it should not let memory for the elements of 
> the training.
>
> What is the size of the data file? OpenNN has been tested with a 
> computer with the same RAM, and we were able to load a data file of 3Gb.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Artelnics/OpenNN/issues/10#issuecomment-224873352>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AS3P1M550DvqpK4DRKTYRj3tDfe6i1s1ks5qJ_71gaJpZM4Iu-dP>.
>

-- 
Françoise LEFEBVRE
IMNC (Imagerie et Modélisation en Neurobiologie et Cancérologie)
Campus d'Orsay - Bât 440
91405 ORSAY Cedex
01 69 15 51 87
