### ISSUE TITLE
can't use LEVENBERG_MARQUARDT_ALGORITHM 

### ISSUE THREAD

**Issue by arthurx70** [Artelnics/OpenNN#101]
I try to use LEVENBERG_MARQUARDT_ALGORITHM to run example in openNN,Does anyone have the same problem？I find the the function named didvide in tensor class is not implemented，and I also find some other bugs...

**Comment by GuillermoArtelnics** [comment]
Hello arthurx,

Can you specify the problem with LEVENBERG_MARQUARDT_ALGORITHM?

Now, we are working to fix this problem in a new version. If you find any more issues, please let us know.
