### ISSUE TITLE
MacOS examples will not build

### ISSUE THREAD

**Issue by edvn0** [Artelnics/opennn#106]
Building the project on macOS 10.15.3 is fine if you exclude the examples. If not, make fails. I saw in the first example that it did not work for linux. How do I make it work for MacOS?

**Comment by GuillermoArtelnics** [comment]
Hello edvn0,

What are the issues you encounter when running the examples?

**Comment by edvn0** [comment]
Disclaimer: I am not a proficient Cpp-programmer and I cannot claim to understand the principles of building programs, but the output of make after declaring the makefile (with cmake and flags) is:
`
[ 62%] Built target opennn
[ 63%] Linking CXX executable airfoil_self_noise
ld: library not found for -l../opennn/Release/opennn
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [examples/airfoil_self_noise/airfoil_self_noise] Error 1
make[1]: *** [examples/airfoil_self_noise/CMakeFiles/airfoil_self_noise.dir/all] Error 2
make: *** [all] Error 2
`

and adding -v to make outputs:
`
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
This program built for i386-apple-darwin11.3.0
`

If I in the makefile (CMakeLists.txt) remove all the add_subdirectory statements, the project builds.

If you feel like this is not an issue, but more of a Stack-question, please just close it.

**Comment by lshoravi** [comment]
fwiw this issue affects me too

**Comment by jandres-artelnics** [comment]
Hi,

Examples are now running on mac (using dev branch).

Thank you for your comments. If you find another error please feel free to open another issue.
