### ISSUE TITLE
Load Network

### ISSUE THREAD

**Issue by Aleoli2** [Artelnics/opennn#109]
I have saved a neural network in a xml file. Now, I wan't to load it, but the function from_XML is commented, so the network cannot be loaded.

**Comment by GuillermoArtelnics** [comment]
That issue is fixed, you can now charge your neural network with from_XML.

I close this issue and thank you for your comment.

**Comment by Aleoli2** [comment]
I have tried to use the constructor of Neural Network with the string of the filename (that calls to load function) and with tinyXML document (to call directly to from_XML) and none have worked. The terminal is closed without exception. If I put a wrong filename, it says that the document cannot be load, so the document is load correctly.
