### ISSUE TITLE
Perform training crashes when used Rectified Linear (Relu) activation function.

### ISSUE THREAD

**Issue by RoberLopez** [Artelnics/opennn#124]

**Comment by jandres-artelnics** [comment]
MNIST using RELU works properly.

Setting perceptron synaptic weights using Glorot and the bias to 0 is needed.

        neural_network.set_parameters_random();
        neural_network.get_first_perceptron_layer_pointer()->set_synaptic_weights_constant_glorot_uniform();
        neural_network.get_first_perceptron_layer_pointer()->set_biases_constant(0);

![image](https://user-images.githubusercontent.com/59603057/91956417-e96b5900-ed04-11ea-9602-6361299ae0e6.png)
