### ISSUE TITLE
"dev" branch : tests/unscaling_layer_test.cpp is broken

### ISSUE THREAD

**Issue by shleym2000** [Artelnics/opennn#127]
As of June 17, 2020 after changes made to _opennn/unscaling_layer_ code the **tests/unscaling_layer_test.cpp** cannot be compiled.

It requires matching adjustments to the new version of the _UnscalingLayer_ class.

**Comment by jandres-artelnics** [comment]
> As of June 17, 2020 after changes made to _opennn/unscaling_layer_ code the **tests/unscaling_layer_test.cpp** cannot be compiled.
> 
> It requires matching adjustments to the new version of the _UnscalingLayer_ class.

Hi @shleym2000 thank you for opening the issue.

We've made some changes, now tests can be compiled.

Thank you.

**Comment by shleym2000** [comment]
Even though the following unit test would definitely fail its assertions, it is now compilable. 

```
   string expression;

   // Test 1

   ul.set(1);
//   ul.set_unscaling_method(UnscalingLayer::NoUnscaling);
   inputs_names.setValues({"x"});
   outputs_names.setValues({"y"});

//   expression = ul.write_expression(inputs_names, outputs_names);

   assert_true(expression.empty() == false, LOG);
   assert_true(expression == "y = x;\n", LOG);
```
I am closing this topic
