### ISSUE TITLE
"dev" branch : unit tests

### ISSUE THREAD

**Issue by shleym2000** [Artelnics/opennn#128]
I had submitted change to the main.cpp module to change the text presented to user as choice.
I did not change calls for tests to run, but I believe that this change would make unit test execution much less confusing.
 
Please, review the following pull request:
https://github.com/Artelnics/opennn/pull/121

**Comment by shleym2000** [comment]
I see that pull request was merged. Thank you.

You can close this issue.

**Comment by jandres-artelnics** [comment]
Thank you @shleym2000 ! Now it's way easier!
