### ISSUE TITLE
Segmentation fault in test suite on OSX 10.10.5

### ISSUE THREAD

**Issue by kommander** [Artelnics/OpenNN#13]
Hi,
Used CMake 3.6, GNU Make 3.81. Compiles successfully.
Trying to run the tests from `./test/data` as it otherwise will complain about missing data files.
Output:

```
...
suite
Test: suite
100
7.00916 0
0 7.00916
6.9987 0
0 6.9987
[1]    8222 segmentation fault  ../opennntests
```

Any experience on darwin with OpenNN?

Thanks for OpenNN!

**Comment by FernandoGomezP** [comment]
We have just uploaded a new version of OpenNN, try to rerun the test with this version.

**Comment by kommander** [comment]
```OpenNN test suite results:
Tests run: 2440
Tests passed: 2440
Tests failed: 0
Test OK
```
👍  Thanks! Looking forward to work and play with it.
