### ISSUE TITLE
NeuralNetwork::to_XML still inactive

### ISSUE THREAD

**Issue by axelspoerl** [Artelnics/opennn#132]
Hi,
in the to_XML function in the latest 4.0 download the main part of the code is still commented out and a neural network cannot be saved for later use.
If I delete the comments, I get a compilation error that inputs_pointer and outputs_pointer are not delcared in this scope - which is effectively true.
So how can I save a neural network for later use?
Brgds
Axel

**Comment by alessandrobrando** [comment]
i need to know to

**Comment by axelspoerl** [comment]
To those in need to save a neural network to an XML file...

Situation:
The function tinyxml2::XMLDocument* NeuralNetwork::to_XML() as defined in line 1487 of neural_network.cpp is en empty shell. It creates an XML document with an empty <NeuralNetwork> section. The function contains a coding for serializing the inputs and outputs, which is commented out. Even if you eliminate the comments, compilation fails. Even if you correct the code, everything but the input and output layers will be missing. I raised this post to get the missing functions but have not received productive feedback by now.

Workaround:
I have written an external function that will serialize a neural network. Code is attached.
The function has the following limitations:
- Pooling, Long Short Term and Recurrent layer serialization is not implemented. Respective layers will be ignored.
- The OpenNN library does not provide a valid function to retrieve the poitner to a perceptron layer. This pointer has been extacted from the general layers pointer vector. This is why the function must be compiled with the -fpermissive option.
- The source code is not really beautiful. But it is excessively commented.

@artelnics: Thanks for the wonderful library, you may use the sourcecode attached to implement the missing functions.
@alessandrobrando Hope it helps you, too.
@community: Includes and compilation command / options are included in the file.

Kind regards
Axel
[nn2xml.cpp.txt](https://github.com/Artelnics/opennn/files/4931245/nn2xml.cpp.txt)

**Comment by alessandrobrando** [comment]
Thanks for the help, but it didn't work on Windows (even using /Ze which is analogous to -fpermissive).

I tried to edit the source code but got stuck in the same problem that you found from only being able to rescue the pointer from the first perceptron layer.

I'm still trying to export the neural network, but unsuccessfully.

**Comment by axelspoerl** [comment]
I am not so familiar with C++ on windows.
In Unix you are able to fetch the pointer with the dynamic cast commands and thus without the fpermissive Compiler option.

**Comment by alessandrobrando** [comment]
I decided to write my own function, from scratch. I managed to make it work and I am already getting the mathematical expressions. Thank you for your commitment. Your dynamic static tip worked. It is such a rush that sometimes things go unnoticed. A hug from Brazil.
