### ISSUE TITLE
Exception with Levenberg Algorithm

### ISSUE THREAD

**Issue by alessandrobrando** [Artelnics/opennn#134]
When designing the training strategy with SSE as a loss method and LEVENBERG as an optimization method, VisualStudio returns the following exception:

MoveSmall8::
        mov     [rax], rcx              ; write eight bytes to destination

How can I fix this?

Thank you.

**Comment by alessandrobrando** [comment]
Solved.

**Comment by GuillermoArtelnics** [comment]
Hello alessandrobrando,

Have you been able to fix the issue?

**Comment by alessandrobrando** [comment]
not yet

**Comment by jandres-artelnics** [comment]
Hi @alessandrobrando  it should be fixed now on dev branch. 

Try it and if you still find the problem please open another issue. 

Thank you for reporting the bug.
