### ISSUE TITLE
How Decide Which Interval Scaling Should Be?

### ISSUE THREAD

**Issue by alessandrobrando** [Artelnics/opennn#136]
I would like standardize my data to an interval [0,1], but by default scale_inputs_minimum_maximum() uses an interval [-1,1].

How do I decide on which interval the data scaling should be?

Thank you.

**Comment by Carlosbarranquero** [comment]
We will implement this functionality in future releases. However, you can implement those changes yourself.
You should modify the following funtions in the dataset class:

* scale_input_minimum_maximum
* scale_target_minimum_maximum

Also you have to modify the calculate_outputs function in scaling_layer class and unscaling_layer class.

Thank you.

**Comment by alessandrobrando** [comment]
thank u
