### ISSUE TITLE
"dev" branch : using unsafe version of fopen()

### ISSUE THREAD

**Issue by shleym2000** [Artelnics/opennn#139]
Recent changes switched from the safe version of fopen_s() to the unsafe fopen(). Stricter compilers consider it errors:

> opennn\ **data_set.cpp** (8084,13): error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
> opennn\ **neural_network.cpp** (2282,13): error C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.

Here is the sample of the current code, where better version is left commented:

> {
>     FILE *pFile;
> //    int err;
> 
> //    err = fopen_s(&pFile, file_name.c_str(), "w");
>     _pFile = fopen(file_name.c_str(), "w");_
>     tinyxml2::XMLPrinter document(pFile);
>     write_XML(document);
>     fclose(pFile);
> }

**Comment by JavierSanchezB** [comment]
As far as we know, `fopen_s` does not work on unix systems by default.
For that reason, we made the change back to standar `fopen`.

**Comment by shleym2000** [comment]
OK, you probably right.
I had to add _CRT_SECURE_NO_WARNINGS definition to compile these projects it in Visual Studio.
