### ISSUE TITLE
win7 build failed

### ISSUE THREAD

**Issue by efimov-denis** [Artelnics/OpenNN#14]
Dear Artelnics,
I just tried to build an example from your repository using Qt 5.5.1 on windows 7 and got these errors:

g++ -static-libgcc -static-libstdc++ -static -Wl,-subsystem,console -mthreads -o ......\OpenNN\examples\simple_function_regression\bin\simple_function_regression.exe debug/main.o  -LD:/opennn/build-opennn-Desktop_Qt_5_5_1_MinGW_32bit-Debug/examples/simple_function_regression/../../opennn/debug/ -lopennn -LD:/opennn/build-opennn-Desktop_Qt_5_5_1_MinGW_32bit-Debug/examples/simple_function_regression/../../tinyxml2/debug/ -ltinyxml2 -LD:/Qt/5.5/mingw492_32/lib -lQt5Guid -lQt5Cored 
D:/opennn/build-opennn-Desktop_Qt_5_5_1_MinGW_32bit-Debug/examples/simple_function_regression/../../opennn/debug/\libopennn.a(data_set.o): In function 'ZN6OpenNN7DataSet24unuse_repeated_instancesEv':
D:\opennn\build-opennn-Desktop_Qt_5_5_1_MinGW_32bit-Debug\opennn/../../OpenNN/opennn/data_set.cpp:1881: undefined reference to 'GOMP_parallel'

etc.

**Comment by houssam11350** [comment]
hi ... 
open file: simple_function_regression.pro
and add:
QMAKE_CXXFLAGS += -std=c++11 -fopenmp -pthread -lgomp
QMAKE_LFLAGS +=  -fopenmp -pthread -lgomp
LIBS += -fopenmp -pthread -lgomp

note that you must make that for all examples:
airfoil_self_noise.pro
breast_cancer.pro
iris_plant.pro
leukemia.pro
.....
etc
