### ISSUE TITLE
double free or corruption (!prev) Aborted (core dumped) Error on Multiple Output Neuron Tophology

### ISSUE THREAD

**Issue by JUNZ1** [Artelnics/opennn#144]
Hello I wanted to tryout your library but faced an error, When i use single neuron output everything is fine, but when i try to make 2 neuron output i get this error
Would you help me know where i do mistake?

Regards..

#include <iostream>
#include <sstream>
#include <time.h>
#include <stdexcept>

// OpenNN includes

#include "opennn.h"

using namespace std;
using namespace OpenNN;

int main(void)
{
    try
    {
        cout << "OpenNN. Simple Function Regression Example." << endl;

        srand(static_cast<unsigned>(time(nullptr)));

        // Data set

        DataSet data_set("/home/baran/Documents/NeuralDesignerProjects/winequality-red.csv", ';', true);
  
        //Line below causes crash if i disable comment
        //data_set.set_column_use(10,OpenNN::DataSet::VariableUse::Target);
        // Variables

        const Vector<string> inputs_names = data_set.get_input_variables_names();
        const Vector<string> targets_names = data_set.get_target_variables_names();

        for(auto eachName : targets_names)
        {
            std::cout<<eachName<<data_set.get_target_variables_number()<<std::endl;
        }

        data_set.split_instances_random();

        const Vector<Descriptives> inputs_descriptives = data_set.scale_inputs_minimum_maximum();
        const Vector<Descriptives> targets_descriptives = data_set.scale_targets_minimum_maximum();

        // Neural network

        const size_t inputs_number = data_set.get_input_variables_number();
        const size_t hidden_perceptrons_number = 5;
        const size_t outputs_number = data_set.get_target_variables_number();

        NeuralNetwork neural_network(NeuralNetwork::Approximation, {inputs_number, hidden_perceptrons_number, outputs_number});
        neural_network.randomize_parameters_normal();
        neural_network.set_inputs_names(inputs_names);
        neural_network.set_outputs_names(targets_names);

        ScalingLayer* scaling_layer_pointer = neural_network.get_scaling_layer_pointer();

        scaling_layer_pointer->set_descriptives(inputs_descriptives);

        UnscalingLayer* unscaling_layer_pointer = neural_network.get_unscaling_layer_pointer();

        unscaling_layer_pointer->set_descriptives(targets_descriptives);

        // Training strategy object

        TrainingStrategy training_strategy(&neural_network, &data_set);

        training_strategy.set_loss_method(TrainingStrategy::NORMALIZED_SQUARED_ERROR);
        training_strategy.set_optimization_method(TrainingStrategy::QUASI_NEWTON_METHOD);
        training_strategy.get_quasi_Newton_method_pointer()->set_loss_goal(1.0e-3);

        const OptimizationAlgorithm::Results optimization_algorithm_results = training_strategy.perform_training();

        return 0;
    }
    catch(exception& e)
    {
        cerr << e.what() << endl;

        return 1;
    }
}

**Comment by alessandrobrando** [comment]
The number of neurons in the last hidden layer must correspond to the number of exits.

**Comment by JUNZ1** [comment]
First of all i would want to thank you for kindly return

I tried below lines again didn't worked for me
        ...
        const size_t inputs_number = data_set.get_input_variables_number();
        const size_t hidden_perceptrons_number = data_set.get_target_variables_number();
        const size_t outputs_number = data_set.get_target_variables_number();
        ...

**Comment by GuillermoArtelnics** [comment]
Hello JUNZ1,

Have you checked that the values introduced in the architecture are correct?
Can you give me your results or issues obtains during the process?

**Comment by JUNZ1** [comment]
Hi 
I just downloaded data from https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/, I just wanted to use it for quick practise of library..

When i try to train using Neural Designer there is no error for two neuron output.. I can train succesfully and tests are also fine.. you can see the ss in the below.. Problem starts with training by code above..
![Screenshot from 2020-07-24 16-15-54](https://user-images.githubusercontent.com/8955210/88400718-038e4f00-cdc9-11ea-9dad-a7cbdb09b5a0.png)

![Screenshot from 2020-07-24 16-22-53](https://user-images.githubusercontent.com/8955210/88401370-f3c33a80-cdc9-11ea-8442-35134fda7376.png)

Regards..

**Comment by JUNZ1** [comment]
I think i found problem,
Suppose that i want to set 2 column as output, i got crash if i set them in a way following
data_set.set_column_use(6,OpenNN::DataSet::VariableUse::Target);
data_set.set_column_use(5,OpenNN::DataSet::VariableUse::Target);

If i set them following i dont get any crash

data_set.set_columns_uses ({OpenNN::DataSet::VariableUse::Input,OpenNN::DataSet::VariableUse::Input,OpenNN::DataSet::VariableUse::Input,OpenNN::DataSet::VariableUse::Input,OpenNN::DataSet::VariableUse::Input,OpenNN::DataSet::VariableUse::Target,OpenNN::DataSet::VariableUse::Target});

Would you confirm please..

Thank you..
