### ISSUE TITLE
Performance and Interface problems..

### ISSUE THREAD

**Issue by JUNZ1** [Artelnics/opennn#145]
Hello guys first of all these issue is just a kindly observation, to support your respectfull efforts i also tried to point the location of the problem too..

Before start i would want to mention that I am just sharing my full 2 day workout on your library, please let me know if i did something wrong as metodology so evereyone can befefit from it.

For clerification i didnt use any data set, i just use data set that already included in test projects below.
 *yacht_hydrodynamics_design
 *yacht_hydrodynamics_production

Observations and My quick solutions

1- Crash Issue:
  I can simply say that program crashes in the current master branch, [master](https://github.com/Artelnics/opennn/commit/aec86e284659601a18ccfa6f509bc230054cc70f)
like declared in the issue #140 
 Quick Solution: just revert software back to the commit wroted as "new version OpenNN", i will explain also why i choose that point for observation & comparison with the current status of the library, yes architecture is changed but core functionalities looks similar..

2. Performance Issue: For this issue I can say that i made two comparison, in two different branches..
   2.1- Current Master Branch: Offcourse there is crash you can forget about it, i dont have output
   2.2- "new version OpenNN" branch: There is no crash but there is a problem already mentioned in #137 
 Just let me show you my screen shot:
This is the output of the regression:
![ss1](https://user-images.githubusercontent.com/8955210/88490926-37bb6880-cf9f-11ea-85c8-ff9db853db63.png)
This is the real data that we must get
"-2.3 0.568 4.78 3.99 3.17 0.325 -> 4.99", 
:-1: Real Data is =5 but Library output is 0.373 ??? :-1: 

3- Depracated Functionalities: That is the point that i can explain the reason why i choose that "new version OpenNN" part
If you have a look that "new version OpenNN" commit, you will see that so many IMPORTANT depracated functionalities in the library
Some of the biggests are : 
   3.1-There is no more NeuralNetwork::write_expression() in the current master branch which was implemented in "new version OpenNN" branch.. I find that feature is the feature most of the people look for, it directly gives the builded expression of the system.. 
   3.2- Moving from Standard C++ containers to the Tensor Containers for output calculation, for example you could use just this interface before the current [master](https://github.com/Artelnics/opennn/commit/aec86e284659601a18ccfa6f509bc230054cc70f)

`vector<double> NeuralNetwork::calculate_outputs_std(const vector<double>& inputs) const
{
    return calculate_outputs(Vector<double>(inputs)).to_std_vector();
}`

These are my observations, i hope it may be usefull for anyone..

**Comment by jandres-artelnics** [comment]
Hi @JUNZ1 

We're trying to fix all the issues in dev branch. As you said, dev branch contains huge changes.

Concerning your second point:

I just tested in dev branch the yatch example, here's a pic. 

![image](https://user-images.githubusercontent.com/59603057/91711113-a20a8e80-eb85-11ea-8299-ed839702e07e.png)

Regarding 3: Write expression is implemented in dev branch and master branch will be updated soon.

Try to use dev branch instead of master since there are major changes that will be moved to master soon.

Thank you for your comments.
