### ISSUE TITLE
Problem loading Dataset (noob)

### ISSUE THREAD

**Issue by Sophia-Cristina** [Artelnics/opennn#150]
First, let me say i'm not advanced in c++.
But well, i used CMake to create a solution for me.
The examples works well, i tested the MNIST example and it compiles and read the data correctly.
However, i'm copying from MNIST to my project and the class "Dataset" is not working, i mean, it compiles, but when i click on the executable it don't works.

Here is my code (comments is when i thought i should use the other methods too, but the problem is the Dataset constructor):
```
int main()
{
    cout << "OpenNN. Attempt to make a GAN." << endl;

    // MAKE DATA:
    CImg<unsigned char> IMG("TestImages/Number1.bmp"); // CImg is an image library, this opens an image
    vector<Point3DFlt> RGB = BitmapRGBMatrix(IMG); // Point3DFlt is my struct, it is just 3 floats, the method adds the pixel value to the vector
    MakeDataSetRGBLine(RGB, 1); // This methods writes a ".csv" file with the pixel data, i made it the same way as the MNIST example training data

    // OPEN DATA:
    DataSet data_set("DATA.csv", ',', false);

    /*data_set.set_input();
    data_set.set_column_use(0, OpenNN::DataSet::VariableUse::Target);
    data_set.numeric_to_categorical(0);
    data_set.set_batch_instances_number(5);

    const Vector<size_t> inputs_dimensions({ 1, 10, 10 });
    const Vector<size_t> targets_dimensions({ 10 });
    data_set.set_input_variables_dimensions(inputs_dimensions);
    data_set.set_target_variables_dimensions(targets_dimensions);

    //const size_t total_instances = 100;
    //data_set.set_instances_uses((Vector<string>(total_instances, "Training").assemble(Vector<string>(60000 - total_instances, "Unused"))));
    data_set.split_instances_random(0.75, 0, 0.25);*/

    int NADA; cin >> NADA;
}
```
I also tried to load the data without my method to write data.
The content of my image that is 10x10 after my method writes the data is:
1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1

The error i receive is "Expression: vector subscript out of range".

**Comment by Sophia-Cristina** [comment]
> your code is commented and you must define the dimensions according to the dataset.

Oh, the commented code was already tested, in fact i tried again, but it still don't work... Does that means the dimensions are wrong? How can i know the proper dimensions? (if that is not much to ask).

**Comment by alessandrobrando** [comment]
your input needs 366 neurons (if i didn't count it wrong), but you put 1: const Vector<size_t> inputs_dimensions({ 1, 10, 10 });

and the number of neurons in the output layer must be equivalent to the number of outputs.

**Comment by Sophia-Cristina** [comment]
Sorry taking long to answer.

I may be saying by naivety, but i can't understand, why the program crashes at "DataSet" constructor line if the problem is dimensions (that are written after the construction)?

Why when i make the program only the "DataSet" constructor, it crashes?

Based on this i may have found the problem, i don't know why i have not tested it sooner, derp...
When i use my method to write a 28x28 single-channel image and use it on the MNIST example, it also breaks, but it don't breaks with their own training data file, so, i think the problem is how my ".csv" file is being rendered.
Explanation image:
![Found the problem](https://user-images.githubusercontent.com/43291594/91006471-d8597400-e5af-11ea-962e-f1c0981cf57e.png)

---

Base on this image i think you can ignore the rest of the comment, but in case you want to know, i tested your solutions.

I tried:
"const Vector<size_t> inputs_dimensions({ 1, 300 });"
"const Vector<size_t> inputs_dimensions({ 1, 300, 10 });"
"const Vector<size_t> inputs_dimensions({ 1, 366 });"
"const Vector<size_t> inputs_dimensions({ 1, 366, 10 });"
"const Vector<size_t> inputs_dimensions({ 1, 300 });"
"const Vector<size_t> inputs_dimensions({ 1, 301 });"
"const Vector<size_t> inputs_dimensions({ 1, 301, 10 });"
"const Vector<size_t> inputs_dimensions({ 301, 10 });"
"const Vector<size_t> inputs_dimensions({ 301 });"
"const Vector<size_t> inputs_dimensions({ 366 });"

The target have 10 outputs because i want the computer vision say to me which number it saw, from "0, 1, 2, 3, 4, 5, 6, 7, 8 and 9", that is the same target dimension in the MNIST example.

By what i saw in the MNIST the input dimension is:
"const Vector<size_t> inputs_dimensions({ 1, 28, 28 });"
Probably becase MNIST Dataset are images sized 28x28.
The first number seems to be the target (one target, i mean, in the training data, the first number is the target number)

**Comment by Sophia-Cristina** [comment]
I FOUND THE SOLUTION!!!
I think there is a problem in the DataSet constructor that DON'T accept ONE LINE AS INPUT!
So i copy pasted in the excel more lines and it worked!
![worknig!](https://user-images.githubusercontent.com/43291594/91007564-af86ae00-e5b2-11ea-8e12-292f8721f22b.jpg)

Sorry wasting you time for such a silly problem!
But, understand me, who could i know it was this issue! :stuck_out_tongue:
