### ISSUE TITLE
How could I contribute

### ISSUE THREAD

**Issue by antgr** [Artelnics/opennn#151]
Is there a way to contribute? I want to open the project in visual studio and run some scenarios, to get a feel of the project from the developer's point of view. Can you give me some instructions on how could I start?

**Comment by shleym2000** [comment]
That could be not the approach authors of the project intended,  but this is how I did it.
1. I ignored project/solution files included by authors
2. In my Visual Studio I had created an empty Library project for OpenNN and added all files from **opennn** subdirectory
3. I had created another empty Console Application project for 1 example project (I chose **examples\logical_operations** first) and added **examples\logical_operations\main.cpp** file to it. I made this Application project dependent on my OpenNN library project

Additional non-obvious, but still easy things to take care about in both projects:
1. Example project's VC++ Directories settings I had to add **openn** directory to the list of the include directories
2. List of Prepocessor Definitions has to include **_CRT_SECURE_NO_WARNINGS** macro

**Comment by jandres-artelnics** [comment]
Hi @antgr .

In "projects" you may find several tasks we're doing. It'd be great if you could do any of those.

@shleym2000 is doing great contributions so bear in mind his/her advice!

Thank you for your willingness to contribute.
