### ISSUE TITLE
Error compiling application using opennn

### ISSUE THREAD

**Issue by herbertamukhuma** [Artelnics/opennn#157]
Hello, am trying to use opennn and it's quite difficult to get started with. Am using Qt and am getting this error.
![IMG20201010181103](https://user-images.githubusercontent.com/37830837/95658955-bba8d980-0b26-11eb-9173-c97433973146.jpg)

**Comment by MrChuse** [comment]
I've described the same error in [my other comment](https://github.com/Artelnics/opennn/issues/156#issuecomment-706564680)

**Comment by jandres-artelnics** [comment]
Hi @herbertamukhuma , 

In which line and file did you found the error? Where is the failed reference to maximum(Eigen ... ) ?

**Comment by herbertamukhuma** [comment]
I was trying to use the dataset class snd that's the error i get. Also trying to build the examples gives the same error

**Comment by jandres-artelnics** [comment]
Hi @herbertamukhuma , 

Master branch is working properly for me using Qt, I don't know why it is not working for you.

You should follow the following steps if you want to run an example:

1.- Update Master Branch
2.- Double click on opennn.pro. This should open the project on Qt.
3.- Configure project.
4.- Choose Release and the example you wanna run (first image attached).
5.- Click run.

If something does not work properly is recommended to clean the project. build>clean all (second image attached).


![image](https://user-images.githubusercontent.com/59603057/95962597-dd47e080-0e06-11eb-9ce1-832800ab29d7.png)


![image](https://user-images.githubusercontent.com/59603057/95964006-a4a90680-0e08-11eb-820a-ff8b9228274e.png)

Thank you for using OpenNN

**Comment by herbertamukhuma** [comment]
Okay, I'll try that

**Comment by jandres-artelnics** [comment]
Following theese steps the major inconvenience you could face should be the path to the dataset, that can be easily replaced in the example main.cpp file.

Please let me know if something does not work.

**Comment by herbertamukhuma** [comment]
I will. I'll get back to it over the weekend

**Comment by jandres-artelnics** [comment]
Hi @herbertamukhuma , 

I'll close the issue. If there are more troubles please feel free to open another issue or contacting us at info@opennn.net

**Comment by herbertamukhuma** [comment]
Okay I will. However your email at times doesn't work. I get the error that your inbox is full. Kindly look into that. Thanks for your assistance

**Comment by jandres-artelnics** [comment]
Oh thank you for reporting that.

I'll take a look at it.

**Comment by herbertamukhuma** [comment]
Hello, seems the maximum function does not have a definition in the statistics.cpp file. Might this be the issue
![Uploading IMG_20201016_130758.jpg…]()
