### ISSUE TITLE
I can't load CSV in python

### ISSUE THREAD

**Issue by TByte007** [Artelnics/opennn#159]
A simple program like this can not for some reason detect the separator 
```
import opennn

data_set = opennn.DataSet("data/simple_function_regression2.csv", ';')

```

>     data_set = opennn.DataSet("data/simple_function_regression2.csv", ';')
> RuntimeError: OpenNN Exception: DataSet class.
> void set_separator(const string&) method.
> Unknown separator: ;.
> 
As far as I can say it should work but it doesn't. Are there any Python examples ?

**Comment by jandres-artelnics** [comment]
Hi @TByte007 ,

I'm afraid the python wrapper is deprecated and by now we're not keeping this functionality for future versions.
