### ISSUE TITLE
Is the opennn python wrapper abandoned?

### ISSUE THREAD

**Issue by attilabibok** [Artelnics/opennn#162]
Hi!

I'm wondering if the opennn python wrapper (https://pypi.org/project/OpenNN/) is abandoned? I see that it had it's latest more than a year ago. Although, the C++ package is well maintained. Do I miss something or did you moved the project from PyPI to somewhere else?

Regards,
Attila

**Comment by jandres-artelnics** [comment]
Hi @attilabibok , 

You're right, OpenNN Python Wrapper is abandoned.
It would be nice to have it in the future but for now we are working on tasks with higher priority.

Thank you for your interest in OpenNN.

Best, 
Jesus
