### ISSUE TITLE
opennn-cuda? support for HIP maybe more usefull also..

### ISSUE THREAD

**Issue by labidus** [Artelnics/opennn#163]
Where is opennn-cuda ? Also the are another lib (HIP) that support CUDA and all others card like AMD that could be used instead of CUDA directly.

**Comment by slomanshield** [comment]
I too have been trying to use the Eigen support with cuda. Haven't been successful. 

Looking at the header files for Eigen it seems there is CUDA support. But when compiling a main.cu  with nvcc there are compiler errors in numerical_differentiation.h. This is with cuda 10.2

Is there any formal documentation on how to use opennn with cuda?

**Comment by labidus** [comment]
I think they did not release all the code related to CUDA.

**Comment by slomanshield** [comment]
ah, shame

**Comment by jandres-artelnics** [comment]
Hi  @labidus and  @slomanshield ,
You're right, we're not going to release the code related to CUDA.
Sorry for the late reply.

Thank you for using OpenNN.
