### ISSUE TITLE
unable to build examples on Ubuntu

### ISSUE THREAD

**Issue by Harsger** [Artelnics/opennn#166]
Dear developers,

I have a similar issue like
https://github.com/Artelnics/OpenNN/issues/100

Unfortunately this problem was not answered satisfyingly.

I am building on Ubuntu 18.04.5 LTS bionic.

My procedure was similar, despite I have experimented 
a bit more with different build directories
(and removing the whole repository 
in order to download it fresh in between).

My error message during/after building is:

```
[ 69%] Linking CXX static library libopennn.a
[ 69%] Built target opennn
Scanning dependencies of target airfoil_self_noise
[ 70%] Building CXX object examples/airfoil_self_noise/CMakeFiles/airfoil_self_noise.dir/main.cpp.o
[ 72%] Linking CXX executable airfoil_self_noise
/usr/bin/ld: cannot find -l../../opennn/Release/opennn
collect2: error: ld returned 1 exit status
examples/airfoil_self_noise/CMakeFiles/airfoil_self_noise.dir/build.make:94: recipe for target 'examples/airfoil_self_noise/airfoil_self_noise' failed
make[2]: *** [examples/airfoil_self_noise/airfoil_self_noise] Error 1
CMakeFiles/Makefile2:185: recipe for target 'examples/airfoil_self_noise/CMakeFiles/airfoil_self_noise.dir/all' failed
make[1]: *** [examples/airfoil_self_noise/CMakeFiles/airfoil_self_noise.dir/all] Error 2
Makefile:105: recipe for target 'all' failed
make: *** [all] Error 2
```

The commands I used are:

```
git clone https://github.com/Artelnics/opennn.git && cd opennn
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release .. && make
```

Due to the message
> /usr/bin/ld: cannot find -l../../opennn/Release/opennn

I have also tried to build it using
> mkdir Release && cd Release

or 
> cd opennn && mkdir Release && cd Release

obtaining the same result/error message.

I would be very pleased for further help.

**Comment by jandres-artelnics** [comment]
Hi @Harsger , 

Can you pull the changes we've made in the dev branch and retry as you did before (with the Release directory)?

I think all should be working by now though you will have to move the data of each example you wanna run as is told in the tutorial:
https://www.opennn.net/documentation/building_opennn.html

Thank you for using OpenNN and for contacting us. 

If you have any issues please let us know.

**Comment by Harsger** [comment]
Hi @jandres-artelnics ,

now the examples work (despite some minor warnings during compilation) .

Many thanks for the fast reply !
