### ISSUE TITLE
Error when buildin opennn project using Visual Studio

### ISSUE THREAD

**Issue by maximeselingue** [Artelnics/opennn#167]
Hello, 

I followed the instruction on your website to build opennn with visual studio, but when  I build opennn subproject, I get the following error : 
*c:\opennn\eigen\unsupported\eigen\cxx11\src/Tensor/TensorEvaluator.h(413): error C2672: 'Eigen::internal::scalar_quotient_op<double,double>::packetOp': no matching overloaded function found*
*c:\opennn\eigen\unsupported\eigen\cxx11\src/Tensor/TensorEvaluator.h(413): error C2782: 'const Packet Eigen::internal::scalar_quotient_op<double,double>::packetOp(const Packet &,const Packet &) const': template parameter 'Packet' is ambiguous*
*c:\opennn\eigen\unsupported\eigen\cxx11\src/Tensor/TensorEvaluator.h(413): error C2784: 'const Packet Eigen::internal::scalar_quotient_op<double,double>::packetOp(const Packet &,const Packet &) const': could not deduce template argument for 'const Packet &' from '__m128i'*

I can't find out what's wrong. Could you please help me to fix this bug ?

**Comment by JavierSanchezB** [comment]
Hello @maximeselingue 

I just checked to see if I can reproduce your error, but every trial has resulted in a successful compilation.

I would need more information about how are you getting that error.

As general tips, make sure you are up to date with either dev or master branches.

**Comment by maximeselingue** [comment]
Hello @JavierSanchezB , thank you for your quick answer ! 
I've give another try to build opennn and it still doesn't work. I've cloned the last version (from branch master) from this hub, then moved to the directory and typed *"cmake ."*. This command worked.  Then, I opened the project on visual studio 2017 and try to build opennn project (right clicking on opennn project and clicking *Build Only opennn*) , and there I still get the error I copied in the previous message. I'm under window 10, using visual studio Community 2017.  
![Error](https://user-images.githubusercontent.com/72188345/105040878-a9620400-5a62-11eb-9d19-c4a05fd1237b.PNG)
I precise I am a beginner in c++, so I don't really know if I did something wrong, but as the instruction for installation are quite simple, I guess not. I don't know what kind of information do you need to fix this issue, so let me know if I can provide more specific information.

**Comment by JavierSanchezB** [comment]
Hello again @maximeselingue 
The only way I have managed to get the same error has been compiling for Win32 (same as can be seen in your screenshot ) instead of x64.
Try compiling for x64 and see if the error persists.

**Comment by maximeselingue** [comment]
Hello @JavierSanchezB , 
You are right, compiling for x64 worked for me. Thank you for your help !
