### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [Artelnics/opennn#175]
current master 

[jw@cn06 build]$ make VERBOSE=1 -j1
/usr/bin/cmake -E cmake_progress_start /data/jw/opennn/build/CMakeFiles /data/jw/opennn/build//CMakeFiles/progress.marks
make  -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/data/jw/opennn/build'
make  -f opennn/CMakeFiles/opennn.dir/build.make opennn/CMakeFiles/opennn.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/opennn /data/jw/opennn/build /data/jw/opennn/build/opennn /data/jw/opennn/build/opennn/CMakeFiles/opennn.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f opennn/CMakeFiles/opennn.dir/build.make opennn/CMakeFiles/opennn.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'opennn/CMakeFiles/opennn.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 39%] Built target opennn
make  -f examples/airfoil_self_noise/CMakeFiles/airfoil_self_noise.dir/build.make examples/airfoil_self_noise/CMakeFiles/airfoil_self_noise.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/airfoil_self_noise /data/jw/opennn/build /data/jw/opennn/build/examples/airfoil_self_noise /data/jw/opennn/build/examples/airfoil_self_noise/CMakeFiles/airfoil_self_noise.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/airfoil_self_noise/CMakeFiles/airfoil_self_noise.dir/build.make examples/airfoil_self_noise/CMakeFiles/airfoil_self_noise.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/airfoil_self_noise/CMakeFiles/airfoil_self_noise.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 40%] Built target airfoil_self_noise
make  -f examples/bankruptcy/CMakeFiles/bankruptcy.dir/build.make examples/bankruptcy/CMakeFiles/bankruptcy.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/bankruptcy /data/jw/opennn/build /data/jw/opennn/build/examples/bankruptcy /data/jw/opennn/build/examples/bankruptcy/CMakeFiles/bankruptcy.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/bankruptcy/CMakeFiles/bankruptcy.dir/build.make examples/bankruptcy/CMakeFiles/bankruptcy.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/bankruptcy/CMakeFiles/bankruptcy.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 42%] Built target bankruptcy
make  -f examples/breast_cancer/CMakeFiles/breast_cancer.dir/build.make examples/breast_cancer/CMakeFiles/breast_cancer.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/breast_cancer /data/jw/opennn/build /data/jw/opennn/build/examples/breast_cancer /data/jw/opennn/build/examples/breast_cancer/CMakeFiles/breast_cancer.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/breast_cancer/CMakeFiles/breast_cancer.dir/build.make examples/breast_cancer/CMakeFiles/breast_cancer.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/breast_cancer/CMakeFiles/breast_cancer.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 44%] Built target breast_cancer
make  -f examples/iris_plant/CMakeFiles/iris_plant.dir/build.make examples/iris_plant/CMakeFiles/iris_plant.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/iris_plant /data/jw/opennn/build /data/jw/opennn/build/examples/iris_plant /data/jw/opennn/build/examples/iris_plant/CMakeFiles/iris_plant.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/iris_plant/CMakeFiles/iris_plant.dir/build.make examples/iris_plant/CMakeFiles/iris_plant.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/iris_plant/CMakeFiles/iris_plant.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 45%] Built target iris_plant
make  -f examples/leukemia/CMakeFiles/leukemia.dir/build.make examples/leukemia/CMakeFiles/leukemia.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/leukemia /data/jw/opennn/build /data/jw/opennn/build/examples/leukemia /data/jw/opennn/build/examples/leukemia/CMakeFiles/leukemia.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/leukemia/CMakeFiles/leukemia.dir/build.make examples/leukemia/CMakeFiles/leukemia.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/leukemia/CMakeFiles/leukemia.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 47%] Built target leukemia
make  -f examples/logical_operations/CMakeFiles/logical_operations.dir/build.make examples/logical_operations/CMakeFiles/logical_operations.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/logical_operations /data/jw/opennn/build /data/jw/opennn/build/examples/logical_operations /data/jw/opennn/build/examples/logical_operations/CMakeFiles/logical_operations.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/logical_operations/CMakeFiles/logical_operations.dir/build.make examples/logical_operations/CMakeFiles/logical_operations.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/logical_operations/CMakeFiles/logical_operations.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 49%] Built target logical_operations
make  -f examples/mnist/CMakeFiles/mnist.dir/build.make examples/mnist/CMakeFiles/mnist.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/mnist /data/jw/opennn/build /data/jw/opennn/build/examples/mnist /data/jw/opennn/build/examples/mnist/CMakeFiles/mnist.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/mnist/CMakeFiles/mnist.dir/build.make examples/mnist/CMakeFiles/mnist.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/mnist/CMakeFiles/mnist.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 51%] Built target mnist
make  -f examples/pima_indians_diabetes/CMakeFiles/pima_indians_diabetes.dir/build.make examples/pima_indians_diabetes/CMakeFiles/pima_indians_diabetes.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/pima_indians_diabetes /data/jw/opennn/build /data/jw/opennn/build/examples/pima_indians_diabetes /data/jw/opennn/build/examples/pima_indians_diabetes/CMakeFiles/pima_indians_diabetes.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/pima_indians_diabetes/CMakeFiles/pima_indians_diabetes.dir/build.make examples/pima_indians_diabetes/CMakeFiles/pima_indians_diabetes.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/pima_indians_diabetes/CMakeFiles/pima_indians_diabetes.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 53%] Built target pima_indians_diabetes
make  -f examples/rosenbrock/CMakeFiles/rosenbrock.dir/build.make examples/rosenbrock/CMakeFiles/rosenbrock.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/rosenbrock /data/jw/opennn/build /data/jw/opennn/build/examples/rosenbrock /data/jw/opennn/build/examples/rosenbrock/CMakeFiles/rosenbrock.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/rosenbrock/CMakeFiles/rosenbrock.dir/build.make examples/rosenbrock/CMakeFiles/rosenbrock.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/rosenbrock/CMakeFiles/rosenbrock.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 55%] Built target rosenbrock
make  -f examples/simple_approximation/CMakeFiles/simple_approximation.dir/build.make examples/simple_approximation/CMakeFiles/simple_approximation.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/simple_approximation /data/jw/opennn/build /data/jw/opennn/build/examples/simple_approximation /data/jw/opennn/build/examples/simple_approximation/CMakeFiles/simple_approximation.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/simple_approximation/CMakeFiles/simple_approximation.dir/build.make examples/simple_approximation/CMakeFiles/simple_approximation.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/simple_approximation/CMakeFiles/simple_approximation.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 56%] Built target simple_approximation
make  -f examples/simple_classification/CMakeFiles/simple_classification.dir/build.make examples/simple_classification/CMakeFiles/simple_classification.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/simple_classification /data/jw/opennn/build /data/jw/opennn/build/examples/simple_classification /data/jw/opennn/build/examples/simple_classification/CMakeFiles/simple_classification.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/simple_classification/CMakeFiles/simple_classification.dir/build.make examples/simple_classification/CMakeFiles/simple_classification.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/simple_classification/CMakeFiles/simple_classification.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 58%] Built target simple_classification
make  -f examples/urinary_inflammations_diagnosis/CMakeFiles/urinary_inflammations_diagnosis.dir/build.make examples/urinary_inflammations_diagnosis/CMakeFiles/urinary_inflammations_diagnosis.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/urinary_inflammations_diagnosis /data/jw/opennn/build /data/jw/opennn/build/examples/urinary_inflammations_diagnosis /data/jw/opennn/build/examples/urinary_inflammations_diagnosis/CMakeFiles/urinary_inflammations_diagnosis.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/urinary_inflammations_diagnosis/CMakeFiles/urinary_inflammations_diagnosis.dir/build.make examples/urinary_inflammations_diagnosis/CMakeFiles/urinary_inflammations_diagnosis.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/urinary_inflammations_diagnosis/CMakeFiles/urinary_inflammations_diagnosis.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 60%] Built target urinary_inflammations_diagnosis
make  -f examples/vehicle_insurances/CMakeFiles/vehicle_insurances.dir/build.make examples/vehicle_insurances/CMakeFiles/vehicle_insurances.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/vehicle_insurances /data/jw/opennn/build /data/jw/opennn/build/examples/vehicle_insurances /data/jw/opennn/build/examples/vehicle_insurances/CMakeFiles/vehicle_insurances.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/vehicle_insurances/CMakeFiles/vehicle_insurances.dir/build.make examples/vehicle_insurances/CMakeFiles/vehicle_insurances.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/vehicle_insurances/CMakeFiles/vehicle_insurances.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 62%] Built target vehicle_insurances
make  -f examples/yacht_hydrodynamics_design/CMakeFiles/yacht_hydrodynamics_design.dir/build.make examples/yacht_hydrodynamics_design/CMakeFiles/yacht_hydrodynamics_design.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/yacht_hydrodynamics_design /data/jw/opennn/build /data/jw/opennn/build/examples/yacht_hydrodynamics_design /data/jw/opennn/build/examples/yacht_hydrodynamics_design/CMakeFiles/yacht_hydrodynamics_design.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/yacht_hydrodynamics_design/CMakeFiles/yacht_hydrodynamics_design.dir/build.make examples/yacht_hydrodynamics_design/CMakeFiles/yacht_hydrodynamics_design.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/yacht_hydrodynamics_design/CMakeFiles/yacht_hydrodynamics_design.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 64%] Built target yacht_hydrodynamics_design
make  -f examples/yacht_hydrodynamics_production/CMakeFiles/yacht_hydrodynamics_production.dir/build.make examples/yacht_hydrodynamics_production/CMakeFiles/yacht_hydrodynamics_production.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/examples/yacht_hydrodynamics_production /data/jw/opennn/build /data/jw/opennn/build/examples/yacht_hydrodynamics_production /data/jw/opennn/build/examples/yacht_hydrodynamics_production/CMakeFiles/yacht_hydrodynamics_production.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f examples/yacht_hydrodynamics_production/CMakeFiles/yacht_hydrodynamics_production.dir/build.make examples/yacht_hydrodynamics_production/CMakeFiles/yacht_hydrodynamics_production.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'examples/yacht_hydrodynamics_production/CMakeFiles/yacht_hydrodynamics_production.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 66%] Built target yacht_hydrodynamics_production
make  -f blank/CMakeFiles/blank.dir/build.make blank/CMakeFiles/blank.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/blank /data/jw/opennn/build /data/jw/opennn/build/blank /data/jw/opennn/build/blank/CMakeFiles/blank.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f blank/CMakeFiles/blank.dir/build.make blank/CMakeFiles/blank.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
make[2]: Nothing to be done for 'blank/CMakeFiles/blank.dir/build'.
make[2]: Leaving directory '/data/jw/opennn/build'
[ 68%] Built target blank
make  -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/depend
make[2]: Entering directory '/data/jw/opennn/build'
cd /data/jw/opennn/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /data/jw/opennn /data/jw/opennn/tests /data/jw/opennn/build /data/jw/opennn/build/tests /data/jw/opennn/build/tests/CMakeFiles/tests.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/data/jw/opennn/build'
make  -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
make[2]: Entering directory '/data/jw/opennn/build'
[ 68%] Linking CXX executable tests
cd /data/jw/opennn/build/tests && /usr/bin/cmake -E cmake_link_script CMakeFiles/tests.dir/link.txt --verbose=1
/usr/bin/c++ -rdynamic CMakeFiles/tests.dir/bounding_layer_test.cpp.o CMakeFiles/tests.dir/conjugate_gradient_test.cpp.o CMakeFiles/tests.dir/convolutional_layer_test.cpp.o CMakeFiles/tests.dir/correlations_test.cpp.o CMakeFiles/tests.dir/cross_entropy_error_test.cpp.o CMakeFiles/tests.dir/data_set_test.cpp.o CMakeFiles/tests.dir/genetic_algorithm_test.cpp.o CMakeFiles/tests.dir/gradient_descent_test.cpp.o CMakeFiles/tests.dir/growing_inputs_test.cpp.o CMakeFiles/tests.dir/growing_neurons_test.cpp.o CMakeFiles/tests.dir/inputs_selection_test.cpp.o CMakeFiles/tests.dir/learning_rate_algorithm_test.cpp.o CMakeFiles/tests.dir/levenberg_marquardt_algorithm_test.cpp.o CMakeFiles/tests.dir/long_short_term_memory_layer_test.cpp.o CMakeFiles/tests.dir/main.cpp.o CMakeFiles/tests.dir/mean_squared_error_test.cpp.o CMakeFiles/tests.dir/minkowski_error_test.cpp.o CMakeFiles/tests.dir/model_selection_test.cpp.o CMakeFiles/tests.dir/neural_network_test.cpp.o CMakeFiles/tests.dir/neurons_selection_test.cpp.o CMakeFiles/tests.dir/normalized_squared_error_test.cpp.o CMakeFiles/tests.dir/numerical_differentiation_test.cpp.o CMakeFiles/tests.dir/perceptron_layer_test.cpp.o CMakeFiles/tests.dir/pooling_layer_test.cpp.o CMakeFiles/tests.dir/probabilistic_layer_test.cpp.o CMakeFiles/tests.dir/pruning_inputs_test.cpp.o CMakeFiles/tests.dir/quasi_newton_method_test.cpp.o CMakeFiles/tests.dir/recurrent_layer_test.cpp.o CMakeFiles/tests.dir/scaling_layer_test.cpp.o CMakeFiles/tests.dir/statistics_test.cpp.o CMakeFiles/tests.dir/stochastic_gradient_descent_test.cpp.o CMakeFiles/tests.dir/sum_squared_error_test.cpp.o CMakeFiles/tests.dir/testing_analysis_test.cpp.o CMakeFiles/tests.dir/training_strategy_test.cpp.o CMakeFiles/tests.dir/unscaling_layer_test.cpp.o CMakeFiles/tests.dir/weighted_squared_error_test.cpp.o -o tests  ../opennn/libopennn.a
/usr/bin/ld: CMakeFiles/tests.dir/correlations_test.cpp.o: in function `CorrelationsTest::test_linear_correlation()':
correlations_test.cpp:(.text+0x1ac): undefined reference to `omp_get_max_threads'
/usr/bin/ld: CMakeFiles/tests.dir/correlations_test.cpp.o: in function `CorrelationsTest::test_spearman_linear_correlation()':
correlations_test.cpp:(.text+0x7d0): undefined reference to `omp_get_max_threads'
/usr/bin/ld: CMakeFiles/tests.dir/correlations_test.cpp.o: in function `CorrelationsTest::test_rank_linear_correlation()':
correlations_test.cpp:(.text+0xca0): undefined reference to `omp_get_max_threads'
/usr/bin/ld: CMakeFiles/tests.dir/correlations_test.cpp.o: in function `CorrelationsTest::test_rank_linear_correlation_missing_values()':
correlations_test.cpp:(.text+0x1350): undefined reference to `omp_get_max_threads'
/usr/bin/ld: CMakeFiles/tests.dir/correlations_test.cpp.o: in function `CorrelationsTest::test_logarithmic_correlation()':
correlations_test.cpp:(.text+0x1f1c): undefined reference to `omp_get_max_threads'
/usr/bin/ld: CMakeFiles/tests.dir/correlations_test.cpp.o:correlations_test.cpp:(.text+0x23a4): more undefined references to `omp_get_max_threads' follow
/usr/bin/ld: CMakeFiles/tests.dir/correlations_test.cpp.o: in function `std::thread::thread<std::function<void ()>, , void>(std::function<void ()>&&)':
correlations_test.cpp:(.text._ZNSt6threadC2ISt8functionIFvvEEJEvEEOT_DpOT0_[_ZNSt6threadC5ISt8functionIFvvEEJEvEEOT_DpOT0_]+0x1c): undefined reference to `pthread_create'
/usr/bin/ld: correlations_test.cpp:(.text._ZNSt6threadC2ISt8functionIFvvEEJEvEEOT_DpOT0_[_ZNSt6threadC5ISt8functionIFvvEEJEvEEOT_DpOT0_]+0x20): undefined reference to `pthread_create'
/usr/bin/ld: ../opennn/libopennn.a(bounding_layer.cpp.o): in function `OpenNN::Layer::Layer()':
bounding_layer.cpp:(.text._ZN6OpenNN5LayerC2Ev[_ZN6OpenNN5LayerC5Ev]+0xa8): undefined reference to `omp_get_max_threads'
/usr/bin/ld: ../opennn/libopennn.a(data_set.cpp.o): in function `OpenNN::DataSet::set_default()':
data_set.cpp:(.text+0xbab0): undefined reference to `omp_get_max_threads'
/usr/bin/ld: ../opennn/libopennn.a(learning_rate_algorithm.cpp.o): in function `OpenNN::LearningRateAlgorithm::set_default()':
learning_rate_algorithm.cpp:(.text+0x400): undefined reference to `omp_get_max_threads'
/usr/bin/ld: ../opennn/libopennn.a(loss_index.cpp.o): in function `OpenNN::LossIndex::set_default()':
loss_index.cpp:(.text+0x5c8): undefined reference to `omp_get_max_threads'
/usr/bin/ld: ../opennn/libopennn.a(optimization_algorithm.cpp.o): in function `OpenNN::OptimizationAlgorithm::OptimizationAlgorithm()':
optimization_algorithm.cpp:(.text+0x154): undefined reference to `omp_get_max_threads'
/usr/bin/ld: ../opennn/libopennn.a(optimization_algorithm.cpp.o):optimization_algorithm.cpp:(.text+0x320): more undefined references to `omp_get_max_threads' follow
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/tests.dir/build.make:629: tests/tests] Error 1
make[2]: Leaving directory '/data/jw/opennn/build'
make[1]: *** [CMakeFiles/Makefile2:947: tests/CMakeFiles/tests.dir/all] Error 2
make[1]: Leaving directory '/data/jw/opennn/build'
make: *** [Makefile:125: all] Error 2
[jw@cn06 build]$

**Comment by debian-user-france1** [comment]
I'm also affected by this issue, but I think the developer has to fix it. It is a compile error

**Comment by attilabibok** [comment]
Jz65jn, bt65rt3c

**Comment by debian-user-france1** [comment]
> 
> Jz65jn, bt65rt3c

What's your problem

**Comment by davidge807** [comment]
Hello @LutzWeischerFujitsu 

Are you still getting the same building issue with the current dev branch version?

**Comment by LutzWeischerFujitsu** [comment]
Just tried current master on x86, Ubuntu. cmake error: cannot find principal_components_layer.cpp.

**Comment by davidge807** [comment]
Hi again @LutzWeischerFujitsu 

As I said, master brunch isn't updated. Dev branch will be merged into master in the following days. Try running current dev, it should fix your error.

Thank you for your interest in OpenNN project.
