### ISSUE TITLE
Iris Demo Maybe incorrect

### ISSUE THREAD

**Issue by JieGH** [Artelnics/opennn#178]
Hi, I ran the Iris demo and had a look at the data_set.xml file, the xml file I generated does not make sense. Could anyone have a look please. I was running commit `8f02ef3f9260d51e035e8669e4a4911394ce7c11`

Could you provide more examples for multi classes classification please. Most of the examples are two classes problems only and basically the same.

examples/iris_plant/main.cpp

Part of data_set.xml, 
This is not right.
```
  <Column Item="4">
         <Name>petal_width</Name>
         <ColumnUse>Target</ColumnUse>
         <Type>Numeric</Type>
      </Column>
```

```
<Columns>
      <ColumnsNumber>5</ColumnsNumber>
      <Column Item="1">
         <Name>sepal_lenght</Name>
         <ColumnUse>Input</ColumnUse>
         <Type>Numeric</Type>
      </Column>
      <Column Item="2">
         <Name>sepal_width</Name>
         <ColumnUse>Input</ColumnUse>
         <Type>Numeric</Type>
      </Column>
      <Column Item="3">
         <Name>petal_lenght</Name>
         <ColumnUse>Input</ColumnUse>
         <Type>Numeric</Type>
      </Column>
      <Column Item="4">
         <Name>petal_width</Name>
         <ColumnUse>Target</ColumnUse>
         <Type>Numeric</Type>
      </Column>
      <Column Item="5">
         <Name>iris_class</Name>
         <ColumnUse>Input</ColumnUse>
         <Type>Categorical</Type>
         <Categories>iris_setosa;iris_versicolor;iris_virginica</Categories>
         <CategoriesUses>Input;Input;Input</CategoriesUses>
      </Column>
```

**Comment by JieGH** [comment]
Terminal Output for the  testing is also not right. It's clearly, the NN is running as a two classes classification mode.
` https://github.com/Artelnics/opennn/blob/8f02ef3f9260d51e035e8669e4a4911394ce7c11/examples/iris_plant/main.cpp#L88
`
```
inputs: 
5.1 3.5 1.4 0.2
6.4 3.2 4.5 1.5
6.3 2.7 4.9 1.8
outputs: 
0.0375369
0.0375369
 0.114579
Confusion: 
19  0
 0 11

```

**Comment by tophe38** [comment]
Hi,

If you build opennn in debug mode, an exception is raise in neural_network.calculate_outputs(inputs), line 96 or iris_plant example  :

EXCEPTION ! OpenNN Exception: ScalingLayer class.
Tensor<type, 2> calculate_outputs(const Tensor<type, 2>&) const method.
Size of inputs (4) must be equal to number of scaling neurons (6).

It's like input data don't have enough columns. Each data rows are directly pass throw a 6 scaling neurons.

**Comment by davidge807** [comment]
Hello @JieGH 

Running commit  `d2c3cc674f87fbb4e9e57d5c387fe32c44c59d6c` should fix your problem. 

That's what I get running Iris demo on my device:
 ``` 
Confusion matrix:
 6  0  0
 0 11  2
 0  0 11
```
