### ISSUE TITLE
Can I load my weights in this neural network ?

### ISSUE THREAD

**Issue by rmmal** [Artelnics/OpenNN#18]
I was searching for a neural network library in c++  to load my weights in it and get the results for some inputs .

So did this library allows me to load my weights ?
if yes what are the format of the weights file ?
and how can i did so ?

Thanks

**Comment by terentjew-alexey** [comment]
Hey, @rmmal.
You need to create an empty [neural network](http://opennn.net/documentation/reference/class_open_n_n_1_1_neural_network.html). Then she set the required configuration, through the creation of [Perceptron](http://opennn.net/documentation/reference/class_open_n_n_1_1_perceptron.html), [layer perceptrons](http://opennn.net/documentation/reference/class_open_n_n_1_1_perceptron_layer.html) or [multilayer perceptron](http://opennn.net/documentation/reference/class_open_n_n_1_1_multilayer_perceptron.html).
Specific weight adjusted methods of the classes of perceptrons.

**Comment by RoberLopez** [comment]
You can save/load the neural network using the save/load methods. 

The format is a XML file that contains the names, weights, activation functions, etc. 

Best regards.
