### ISSUE TITLE
"dev" branch: suggested cleaning

### ISSUE THREAD

**Issue by shleym2000** [Artelnics/opennn#181]
The following items in the "dev" branch are remnants of local tests and can be removed form the published codebase:

- **bash.exe.stackdump** file
- **tests/tests.dir** directory
- **blank/blank.dir** directory
- **opennn/data_set.h~RF3a38a9.TMP** file
- **opennn/long_short_term_memory_layer.h~RF195283be.TMP** file

**Comment by davidge807** [comment]
Hi @shleym2000 

Thank you very much for your contribution and interest in OpenNN.
