### ISSUE TITLE
Wrong check in debug mode

### ISSUE THREAD

**Issue by tophe38** [Artelnics/opennn#183]
Hi,

In weighted_squared_error.cpp, line 169, check() call must be comment out, since neural_network_pointer data member isn't set yet.

TrainingStrategy constructor with NeuralNetwork and DataSet parameters, call first set_loss_index_data_set_pointer() then set_loss_index_neural_network_pointer() .

**Comment by davidge807** [comment]
Hi @tophe38 

TrainingStrategy constructor has been changed according to your contribution. Now, constructor calls first set_loss_index_neural_network_pointer(), then set_loss_index_data_set_pointer().

Thank you very much for your comment and interest in OpenNN.
