### ISSUE TITLE
Dropout Layer

### ISSUE THREAD

**Issue by DireWolf117** [Artelnics/opennn#186]
Hello,
Is there any implementation of a dropout layer in this library or is there an easy way to modify the library to support a dropout layer? In other words what does one have to look out for when creating a new layer type?
Thank you

**Comment by davidge807** [comment]
Hi @DireWolf117 

You can copy files like `perceptron_layer.h` and `perceptron_layer.cpp` to create the Dropout layer. Moreover, you can search (Ctrl+Alt+F) for "PerceptronLayer" and add "DropoutLayer" wherever it's necessary. We hope that this is clear and easy for you.

Thank you very much for your comment and interest in OpenNN.
