### ISSUE TITLE
Forcasting

### ISSUE THREAD

**Issue by frozenemberz** [Artelnics/opennn#199]
Before I keep looking into this issue I was just wondering if the airline forecasting example is working?

If not you can disregard.

It looks like the data set is automatically transformed into a forecasting problem before the transform_time_series function is called and the number of inputs variables numbers is zero and the number of Target variables is 114 and the number of samples is 144. linear regression analysis gives me pretty random results but a lot of the times the slope is zero and the y-intercept is 1. I thought this might have been a scaling issue but I wasn't sure how to address the issue since I'm not quite sure what the input is? When I calculate outputs for the neural network and pass in data_set.get_data it gets me values from 0 to 1 when the values should most likely be in the 800 range.

**Comment by frozenemberz** [comment]
okay so it looks like the data file from the example website does not work properly. if I use the data set in the open nnn/dataset/airline file and adjust it so it doesn't error out because the date is before 1970 it loads the data properly. when performing linear regression though the results are still sometimes not a number or just really bad. is there some sort of scaling I have to do? is there a different working example for forcasting?

**Comment by frozenemberz** [comment]
I think I just don't understand how to use OpenNN yet... apologies

**Comment by xinsuinizhuan** [comment]
> I think I just don't understand how to use OpenNN yet... apologies

I  don't understand how to use OpenNN, yet. They don't support more example about Forcasting. the Forcasting example int 4.0 version could not work.
