### ISSUE TITLE
Wrong order of parameters in the constructor of the class DataSet

### ISSUE THREAD

**Issue by terentjew-alexey** [Artelnics/OpenNN#20]
Hello.

In my project I am doing a data set on my own:

`columnsDS = 14; rowsDS = 6131;
dataSet = new DataSet( columnsDS, rowsDS );`
...
`if( newRow.size() == columnsDS ) {dataSet->set_instance( idxRow, newRow ); }`

But the program will throw an exception:
"OpenNN Exception: DataSet class.\n"
"void set_instance(const size_t&, const Vector<double>&) method.\n"
"Size must be equal to number of variables.\n"

Debug:
![2017-01-29_14-41-39](https://cloud.githubusercontent.com/assets/13602601/22403760/2b6a2a30-e632-11e6-8798-06433f4a70aa.png)

I write code according to the documentation:
"It comprises a data matrix in which columns represent variables and rows represent instances."

**Comment by terentjew-alexey** [comment]
You have options in the [documentation](http://www.opennn.net/documentation/reference/class_open_n_n_1_1_data_set.html#a8df7864b1c77a5c47dccead9c32bacc1) differ from the parameters of the [code](https://github.com/Artelnics/OpenNN/blob/master/opennn/data_set.cpp#L58).

**Comment by FernandoGomezP** [comment]
We were working in a new version of OpenNN and the documentation wasn't updated. We have just uploaded a new version of the documentation and the code.

**Comment by terentjew-alexey** [comment]
Thank you.

offtopic.
What caused such an approach is the location of elements in the class Matrix:
`rows_number*column+row`
but not :
`columns_number*row+column`

I try to run the second option, but do not pass the tests in the "matrix dot vector" and "matrix dot matrix"
