### ISSUE TITLE
Convolutional layer

### ISSUE THREAD

**Issue by Lxy85** [Artelnics/opennn#202]
Hello, I saw that someone combined neural networks in the previous question, but when I used the convolutional layer in the combination process, it showed that it was under development. How can I use the convolutional layer?

**Comment by Lxy85** [comment]
@IvanVolosyuk Hello, I saw your previous question, I want to ask how you use the convolutional layer？

**Comment by IvanVolosyuk** [comment]
I don't. I looked at the examples and that was it.

**Comment by Lxy85** [comment]
> I don't. I looked at the examples and that was it.

Thank you

**Comment by davidge807** [comment]
Hi @Lxy85, as you mentioned, convolutional layers are under development and cannot be used. They will be available soon.
Meanwhile, you can treat your problem as an approximation project and solve it using dense Layers.
