### ISSUE TITLE
Build fail on Ubuntu 20.04.3 LTS 

### ISSUE THREAD

**Issue by iceburn-pt** [Artelnics/opennn#203]
After reading on another open issue to use the dev branch if I encountered any issues I did. First I added  a apparently missing
#include < cfloat > to opennn/neurons_selection.h.
After this I get the same error I get from the main branch:

 44%] Linking CXX executable airfoil_self_noise
/usr/bin/ld: ../../opennn/libopennn.a(data_set.cpp.o): in function `OpenNN::DataSet::read_bmp()':
data_set.cpp:(.text+0x24bab): undefined reference to `std::experimental::filesystem::v1::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: data_set.cpp:(.text+0x24c35): undefined reference to `std::experimental::filesystem::v1::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: data_set.cpp:(.text+0x24d84): undefined reference to `std::experimental::filesystem::v1::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: data_set.cpp:(.text+0x24e0e): undefined reference to `std::experimental::filesystem::v1::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: data_set.cpp:(.text+0x251a9): undefined reference to `std::experimental::filesystem::v1::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: data_set.cpp:(.text+0x2520b): undefined reference to `std::experimental::filesystem::v1::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: ../../opennn/libopennn.a(data_set.cpp.o): in function `std::experimental::filesystem::v1::__cxx11::path::path(std::experimental::filesystem::v1::__cxx11::path&&)':
data_set.cpp:(.text._ZNSt12experimental10filesystem2v17__cxx114pathC2EOS3_[_ZNSt12experimental10filesystem2v17__cxx114pathC5EOS3_]+0x63): undefined reference to `std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../../opennn/libopennn.a(data_set.cpp.o): in function `std::experimental::filesystem::v1::__cxx11::path::path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
data_set.cpp:(.text._ZNSt12experimental10filesystem2v17__cxx114pathC2EONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZNSt12experimental10filesystem2v17__cxx114pathC5EONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x50): undefined reference to `std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../../opennn/libopennn.a(data_set.cpp.o): in function `std::experimental::filesystem::v1::__cxx11::path::clear()':
data_set.cpp:(.text._ZNSt12experimental10filesystem2v17__cxx114path5clearEv[_ZNSt12experimental10filesystem2v17__cxx114path5clearEv]+0x24): undefined reference to `std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../../opennn/libopennn.a(data_set.cpp.o): in function `std::experimental::filesystem::v1::__cxx11::directory_iterator::directory_iterator(std::experimental::filesystem::v1::__cxx11::path const&)':
data_set.cpp:(.text._ZNSt12experimental10filesystem2v17__cxx1118directory_iteratorC2ERKNS2_4pathE[_ZNSt12experimental10filesystem2v17__cxx1118directory_iteratorC5ERKNS2_4pathE]+0x2a): undefined reference to `std::experimental::filesystem::v1::__cxx11::directory_iterator::directory_iterator(std::experimental::filesystem::v1::__cxx11::path const&, std::experimental::filesystem::v1::directory_options, std::error_code*)'
/usr/bin/ld: ../../opennn/libopennn.a(data_set.cpp.o): in function `std::experimental::filesystem::v1::__cxx11::path::path<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::experimental::filesystem::v1::__cxx11::path>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
data_set.cpp:(.text._ZNSt12experimental10filesystem2v17__cxx114pathC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES3_EERKT_[_ZNSt12experimental10filesystem2v17__cxx114pathC5INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES3_EERKT_]+0x74): undefined reference to `std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../../opennn/libopennn.a(data_set.cpp.o): in function `std::iterator_traits<std::experimental::filesystem::v1::__cxx11::directory_iterator>::difference_type std::__distance<std::experimental::filesystem::v1::__cxx11::directory_iterator>(std::experimental::filesystem::v1::__cxx11::directory_iterator, std::experimental::filesystem::v1::__cxx11::directory_iterator, std::input_iterator_tag)':
data_set.cpp:(.text._ZSt10__distanceINSt12experimental10filesystem2v17__cxx1118directory_iteratorEENSt15iterator_traitsIT_E15difference_typeES6_S6_St18input_iterator_tag[_ZSt10__distanceINSt12experimental10filesystem2v17__cxx1118directory_iteratorEENSt15iterator_traitsIT_E15difference_typeES6_S6_St18input_iterator_tag]+0x3b): undefined reference to `std::experimental::filesystem::v1::__cxx11::directory_iterator::operator++()'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/airfoil_self_noise/CMakeFiles/airfoil_self_noise.dir/build.make:85: examples/airfoil_self_noise/airfoil_self_noise] Error 1
make[1]: *** [CMakeFiles/Makefile2:391: examples/airfoil_self_noise/CMakeFiles/airfoil_self_noise.dir/all] Error 2
make: *** [Makefile:106: all] Error 2

Any ideas?

**Comment by davidge807** [comment]
Hi @iceburn-pt, we've modified some files like data_set.cpp in order solve your building error (changes committed in dev branch).

It's now properly working but if you experiment any bug, try running the following version (3 Dec):
[7397b3230ecaa6bac254bcaa98ab2efa8477e8b6](https://github.com/Artelnics/opennn/tree/7397b3230ecaa6bac254bcaa98ab2efa8477e8b6)

Thank you very much for your comment and interest in OpenNN.
