### ISSUE TITLE
dev branches，VS2019, line 10239 in data_set.cpp, info_img = image_paths[i].u8string();

### ISSUE THREAD

**Issue by xinsuinizhuan** [Artelnics/opennn#213]
dev branches，VS2019, line 10239 in data_set.cpp, compile errors:
info_img = image_paths[i].u8string();

could not give a u8string to string

**Comment by davidge807** [comment]
Hi @xinsuinizhuan 

This error has been fixed (dev branch) in the commit number [b6362f1](https://github.com/Artelnics/opennn/commit/b6362f18a9d1a06d47d2b31f6250ca5378ead947). 

Thank you very much for your comment and interest in OpenNN.
