### ISSUE TITLE
DEV branch: Please consider minor issue fix in PR #221

### ISSUE THREAD

**Issue by shleym2000** [Artelnics/opennn#222]
https://github.com/Artelnics/opennn/pull/221

It is very minor issue preventing compiling of the unit tests. It is possible that MASTER branch needs the same fix.

**Comment by shleym2000** [comment]
#221

**Comment by davidge807** [comment]
Hi @shleym2000 

The pruning inputs algorithm has been removed from the OpenNN library. Therefore, these changes are not necessary.

Thank you for your comment and interest in OpenNN, David.
