### ISSUE TITLE
calculate errors function - the error type that is stored in errors Tensors - index # 4 

### ISSUE THREAD

**Issue by leondavi** [Artelnics/opennn#225]
https://www.opennn.net/documentation/reference/testing__analysis_8cpp_source.html 
line 664. 

Errors in errors Tensor within function TestingAnalysis::calculate_errors()
are numbered from 0 to 4. 

However, in documentation there are only 4 calculated errors: 
    Sum squared error.
    Mean squared error.
    Root mean squared error.
    Normalized squared error.

What is the 5th error (index number 4)?

**Comment by davidge807** [comment]
Hi @leondavi 

Testing Analysis function calculate_errors calculates the following errors:

Sum squared error.
Mean squared error.
Root mean squared error.
Normalized squared error.
Minkowski error. 

Thank you for your question and your interest in the OpenNN library.
