### ISSUE TITLE
unscale_mean_standard_deviation is not inverse of scale_mean_standard_deviation if mean is ~0

### ISSUE THREAD

**Issue by Roger13h** [Artelnics/opennn#228]
void scale_mean_standard_deviation(Tensor<type, 2>& matrix,
                                   const Index& column_index,
                                   const Descriptives& column_descriptives)

void unscale_mean_standard_deviation(Tensor<type, 2>& matrix, 
                                  const Index& column_index, 
                                   const Descriptives& column_descriptives)

It will just set the  column to  intersect(MAX, or MIN)  if the  mean is  < 1e-3  

file =   scaling.cpp``

**Comment by davidge807** [comment]
Hi @Roger13h 

Thank you very much for your comment. This bug has been fixed in commit [c67ad5b](https://github.com/Artelnics/opennn/commit/c67ad5b376b9d36e8a8d4c6997842500a8eaaec8).

Thank you very much for your interest in OpenNN library.

**Comment by Roger13h** [comment]
You sure this  [c67ad5b]  seems to be a fix to some "Hello OpenNN!"  program
