### ISSUE TITLE
CMake Issue With Compiling Latest "Master" Branch Library

### ISSUE THREAD

**Issue by programming-ellie** [Artelnics/opennn#230]
When using the DataSet class in my own code, I received undefined references to the TextAnalytics and RegionBasedObjectDetector class.

Using NM I found that when compiling the library, these to files were not being compiled, leaving a bunch of undefined reference errors when DataSet class is used.

I first tried adding them in alphabetical order to CMakeLists.txt in the opennn directory, and NM showed that by compiling the files after DataSet, the symbols were left undefined when DataSet was compiled, but would later be defined under different names when the respective file was compiled. When listed before DataSet, the symbols were defined.

To fix this, I edited the CMakeLists.txt in the "opennn" director to include "text_analytics.cpp" and "region_based_object_detector.cpp" in the top of the file list. 

After compiling the library, all the undefined references were gone.

Also, when compiling, I have to set the CMAKE_BUILD_TYPE to "Release" otherwise I am guaranteed to have a table overflow error. Not sure if this is related to my own compiler, but it feels important to mention in case anyone else has this issue.

Compiled with Mingw64 under MSYS2, GCC Version 12.1.0Rev2
Build Steps:
Download master branch
Open in CMake
Configure
Set CMAKE_BUILD_TYPE to "Release"
Turn off tests, blank, example build targets
Configure
Generate
mingw32-make

My edited CMakeLists.txt:
[CMakeLists.txt](https://github.com/Artelnics/opennn/files/9271634/CMakeLists.txt)

**Comment by davidge807** [comment]
Hi @programming-ellie 

This cmake bug has just been fixed in "dev" and "master" branches. Furthermore, "Debug" build type should be working also now.
I hope these changes solve your problem. 

Thank you for your comment and interest in OpenNN.
