### ISSUE TITLE
Compiling the code

### ISSUE THREAD

**Issue by TidelyPom** [Artelnics/opennn#233]
Hi 

I am trying to compile the opennn source code in Ubuntu 16.04 but I am getting the following error message : 
"/.../opennn-master/opennn/data_set.h:923:91: error: array must be initialized with a brace-enclosed initializer"
I can get past this by changing the CMAKE_CXX_COMPILER from c++ to gcc7, in this case it compiles but when I try to compile 
the airfoil example it doesn't want to.

So my question is : shall I compile with C++ or with gcc7. If I need to compile with c++ how do solve this bug ?

Thank you

**Comment by davidge807** [comment]
Hi @TidelyPom 

Can you please attach an image or a screenshot of the compiling error?

**Comment by TidelyPom** [comment]
![image bug openNN](https://user-images.githubusercontent.com/54140007/186688136-d2b9dd5a-2f12-4a92-97d0-d2eba5e5b7c7.png)

Here it is

**Comment by davidge807** [comment]
What compiling configuration are you running? (compiler, compiler version and c++ version)

**Comment by TidelyPom** [comment]
Sorry for the late reply : I have problems with my Ubuntu 16.04 LTS setup at the moment, I tried to upgrade to 18.04 but the upgrade process crashed so I don't have access to the info you are requesting at the moment. I will sort this out, start again and get back to you if needed.

Thank you

**Comment by davidge807** [comment]
Hi again @TidelyPom 

Is there any new information about the issue that you may provide us?

**Comment by TidelyPom** [comment]
Hello

Basically the issue is either I compile openn only with gcc7 and it works but when I try to compile one of the examples it crashes. Or I try to compile with c++ compiler and I get the message described above.

**Comment by davidge807** [comment]
Hi @TidelyPom 

We've just lunched v6.0.0. Can you try to compile it and tell me if your problem persists?

**Comment by TidelyPom** [comment]
Hi 
Sorry about the late reply, I eventually got my Ubuntu 22.04 setup to work. I have managed to compile opennn and run one example (airfoil_self_noise). 
Thank you
