### ISSUE TITLE
Please consider (re)moving `using namespace std;` in all header files

### ISSUE THREAD

**Issue by lSoleyl** [Artelnics/opennn#234]
For example data_set.h (which gets included by opennn.h) has following directives:
```
using namespace std:
using namespace Eigen;
namespace OpenNN
{
  ...
}
```

This means that after I include opennn.h, I have to use fully qualified names for my own types if their names conflict with a type from std or Eigen.

This also causes following [compilation error](https://developercommunity.visualstudio.com/t/error-c2872-byte-ambiguous-symbol/93889) when the project needs to include the Header <Ole2.h> because `using namespace std;` causes the type `byte` to be ambiguous and there is sadly no way to "unuse" a namespace.

Please consider at least moving the using declarations **into** the OpenNN namespace like this:
```
namespace OpenNN
{
  using namespace std:
  using namespace Eigen;
  ...
}
```
to limit the scope of the using directive to only the OpenNN namespace

AFAIK using the `using namespace` directive in a library header is [considered bad coding practice anyway](https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice).

**Comment by knshkp** [comment]
would you assign this task to me i will solve that
