### ISSUE TITLE
Add More Datasets

### ISSUE THREAD

**Issue by knshkp** [Artelnics/opennn#235]
Can I add more datasets in that because it have very less datasets and you have missed very common datasets that every begineer want

**Comment by knshkp** [comment]
assign this task to me i will add all the datasets that evry begineer wanr

**Comment by davidge807** [comment]
Hi @knshkp 

OpenNN allows you to upload any dataset you want. Nevertheless, it has an example for each project type and other essential features.

If you have any problem trying to upload your datasets, don't hesitate to get in touch with us.

Thank you for your comment and interest in OpenNN!

**Comment by knshkp** [comment]
Yeah actually from the few days i will got suffer from a aid so am not able to open my laptop and now am well could u open me the issues
