### ISSUE TITLE
Errors in data_set.cpp during build

### ISSUE THREAD

**Issue by tomasNeuge** [Artelnics/opennn#236]
I'm trying to build openNN in visual studio 2022 but I am still getting several compiler errors in data_set.cpp. I am building openn project in release mode first according to manual.

![CaptureError](https://user-images.githubusercontent.com/101048956/189311525-0ecc8e55-3308-4f76-a374-97566768c2e6.PNG)

**Comment by davidge807** [comment]
Hi @tomasNeuge 

Can you please tell me what branch are you trying to compile?

**Comment by bonsalty** [comment]
My question is if there is anybody who managed to compile 5.05 in VS2022 and what happened with simplicity?
The old 0.9 had a seperated proper "build" directory and was working fine.  

1) Some of these versions pop up with a compiler setting where the default is Intel C++! There is no such thing for VS. Its
set to 2019 in V5.05 which should work fine
2) Unless the target location is set to static folder "Unable to create directory "D:\opennn\opennn\Release\" 
and it cant locate any of the files.

The 5.05 version sln is just messed up!

**Comment by davidge807** [comment]
Hi @bonsalty 

V5.05 was launched more than a year ago. I recommend you using v6.0.0 (just released).

Thank you very much for your comment and interest in OpenNN library.

**Comment by davidge807** [comment]
@tomasNeuge 

May you try to compile version v6.0.0 and tell me if the problem persists? Thanks.

**Comment by Titirez5** [comment]
I have the exact same issue, please help:
![OpenNN_BuildError](https://user-images.githubusercontent.com/6398690/219671046-d7c7ea90-74b3-49e8-abac-7f20207db8f8.PNG)

**Comment by LukeTheEngineer** [comment]
I was facing this same issue regarding building OpenNN using Visual Studio and switching to my Linux Distro. I would always run into the Data_set.cpp error and the specific error was remove_padding and other issues. I thought I was building it wrong until I saw this forum after already giving up.

**Comment by leondavi** [comment]
I have an issue compiling opennn version 6.0.3 on Ubuntu 22.04
![image](https://user-images.githubusercontent.com/18975070/231913430-fb041e27-f898-4396-878f-5bbf484bd8e5.png)

**Comment by leondavi** [comment]
> I was facing this same issue regarding building OpenNN using Visual Studio and switching to my Linux Distro. I would always run into the Data_set.cpp error and the specific error was remove_padding and other issues. I thought I was building it wrong until I saw this forum after already giving up.

Try former version at the moment until the fix this issue.
v6.0.0 compiled successfully on my machines.

**Comment by davidge807** [comment]
Hello everyone,

We are happy to announce that after some work and effort, we have finally found a solution to the error in the "data_set.cpp" file when compiling OpenNN using CMake. We have run a series of tests and have confirmed that the error has been successfully resolved.

We invite you to try commit ff2a005 of the dev branch of OpenNN and let us know if you experience any other problems or errors. If you find any other error, please do not hesitate to inform us so that we can address it and resolve it.

We want to take this opportunity to thank everyone for their valuable contributions, comments, and interest in OpenNN. Thank you all and we hope that this bug is fixed for everyone!

**Comment by manumastro** [comment]
> I have an issue compiling opennn version 6.0.3 on Ubuntu 22.04 ![image](https://user-images.githubusercontent.com/18975070/231913430-fb041e27-f898-4396-878f-5bbf484bd8e5.png)
> 
> v6.0.0 doesn't have this compilation issue.

Hi, can i ask you your compilation environment?
