### ISSUE TITLE
Computing gradient of a neural network

### ISSUE THREAD

**Issue by cpraveen** [Artelnics/opennn#240]
I am not sure this is the right place to ask such questions. If there is a different forum for this, please tell me.

Suppose I have trained a neural network

```
x = input
y = output
y = N(x)
```

can I compute 

```
grad y(x) = dN/dx
```

in opennn ? Are there any examples of such feature ?

**Comment by davidge807** [comment]
Hi @cpraveen 

OpenNN doesn't allow symbolic differentiation. Nevertheless, there are methods in `numerical_differentiation.h` that allow to approximate the derivatives of functions using OpenNN. You should check this file and methods.

Thank you for your question, David.

**Comment by cpraveen** [comment]
For training, one would need some derivatives of the neural network wrt the weights and biases. I suppose these are computed with back propagation. Is it not possible to use the same technique to compute derivatives wrt the input ?
