### ISSUE TITLE
Discrepancies between tutorials on openNN website and latest code

### ISSUE THREAD

**Issue by TidelyPom** [Artelnics/opennn#249]
Hi 
There are differences between the tutorial on the openNN website and the software as downloaded from the GitHub portal. Do they matter and is there a way to get hold of up to date tutorials ?
Thank you

**Comment by davidge807** [comment]
Hi @TidelyPom

Most of these differences are in the "Calculate outputs" section of each example. That's caused a refactoring that we did few weeks ago. 

We'll update them in the following days. If you have any doubt about them, feel free to create a question/issue in this forum. 

Thank you for your comment and interest in OpenNN library!
