### ISSUE TITLE
#ifndef guards for header files

### ISSUE THREAD

**Issue by shleym2000** [Artelnics/opennn#250]
First, I noticed that https://github.com/Artelnics/opennn/blob/master/opennn/config.h does not have an #ifndef guard and throws warnings because its content gets compiled multiple times. Then I check the style of the #ifndef guards used in other header files.

The names are basically the file names, like _#ifndef CODIFICATION_H_ for _codification.h_ file. And the file names are so simple, that many libraries have the same file names.

No wonder that _#ifndef CONFIG_H_ guard would collide with many other libraries or application codebases.

**But you need to guard every header file of your library.**

Here is what I propose.

**Using any tool you generate UUID for the library. For example, you can use online tool https://www.uuidgenerator.net/ or https://www.uuidtools.com/v4

Then you use this one UUID as a suffix to the names of the macros guarding all of the header files in the OpenNN library.
You just have to replace '-' with '_' in the generated UUID.**

That would make guards not colliding with any other library.

For example

> #ifndef CONFIG_H_13b8cdd7_c529_4e9d_9897_28e005a457f8
> #define CONFIG_H_13b8cdd7_c529_4e9d_9897_28e005a457f8
> ...
> #endif

> #ifndef CODIFICATION_H_13b8cdd7_c529_4e9d_9897_28e005a457f8
> #define CODIFICATION_H_13b8cdd7_c529_4e9d_9897_28e005a457f8
> ...
> #endif

**Comment by davidge807** [comment]
Hi @shleym2000 

Thank you very much for your suggestion and comment. We'll take it into account.
