### ISSUE TITLE
ofstream is ambiguous

### ISSUE THREAD

**Issue by adventurist** [Artelnics/opennn#262]
Current master commit: `5a988bf4e97b0c95cc49a29a109b22b26812f547`
Compiler: `g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0`

Error:
```
optimization_algorithm.cpp:534:5: error: reference to ‘ofstream’ is ambiguous
  534 |     ofstream file;
```

Assuming that is supposed to be `std::ofstream`

**Comment by davidge807** [comment]
Solved in dev branch.
