### ISSUE TITLE
optimization_algorithm.cpp Line 534 needs to be std::ofstream

### ISSUE THREAD

**Issue by echo-luna** [Artelnics/opennn#268]
Line 534 of optimization_algorithm.cpp  needs its namespace defined; throws errors in mingw32-make
`ofstream file;` -> `std::ofstream file;`
compiler: mingw-w64-x86_64-gcc 12.1.0-2
used: cmake-gui, mingw32-make

**Comment by davidge807** [comment]
Duplicated of 267
