### ISSUE TITLE
failed to compile on Ubuntu 22.10 x86/64 

### ISSUE THREAD

**Issue by bstarynk** [Artelnics/opennn#269]
Hello

When cloning your commit  5a988bf4e9 (under `/usr/src/Libs/opencnn`) on Ubuntu 22.10 x86/64 (AMD Ryzen Threadripper 2970WX desktop) your library fails to compile (using `mkdir _build; cd _build; cmake ..`)

Probably because `/home/iker/Escritorio/API/OPENNN_repositorio/opennn` is built-in your CMakeCache.txt file.

We could be interested in using your opennn library in the RefPerSys open source symbolic  artificial intelligence project on http://refpersys.org/ and C++ code under https://github.com/RefPerSys/RefPerSys (its current commit in end of march 2023 is [30ce204](https://github.com/RefPerSys/RefPerSys/commit/30ce2048f526282d0fc86692f0f96367158dabaf)...)

For more details, contact me (Basile Starynkevitch) by email : at office (CEA LIST, see https://list.cea.fr/ ...) to basile.starynkevitch@cea.fr or at home (near Paris) to basile@starynkevitch.net

Regards.

**Comment by davidge807** [comment]
Hi @bstarynk 

We have recently made changes in the Master branch, could you try to compile the last commit of this branch? 

More particularly, commit number da871be621376be4764ecb11915bbefc9bdb1ecb.
