### ISSUE TITLE
Compilation error on Ubuntu 22.04

### ISSUE THREAD

**Issue by leondavi** [Artelnics/opennn#271]
Ubuntu 22.04 
Branch SHA 6f8a43bc8d0a42f4546a7010f67210bf4f1133d6 
gcc/g++ version - 11.3.0

I get the following compilation error: 
![Screenshot 2023-05-07 at 9 10 55](https://user-images.githubusercontent.com/18975070/236660859-0fac092c-338e-4ec0-bb71-c61348646323.png)

Compilation passes on the same system with no issue when switching to opennn version 6.0.0

**Comment by leondavi** [comment]
![Screenshot 2023-05-25 at 1 46 29](https://github.com/Artelnics/opennn/assets/18975070/88e12ca7-0b1a-40fb-9bc4-18d7f67f695c)

**Comment by davidge807** [comment]
Changed in OpenNN v6.0.4 (pre-release)!

Thanks for your aportation @leondavi
