### ISSUE TITLE
win10 build failed

### ISSUE THREAD

**Issue by giacomo87** [Artelnics/OpenNN#28]
Dear Artelnics,
I tried to build an example from your repository using Qt 5.8.0 on windows 10 and got these kinds of errors related to GOPM_parallel and omp's functions:

C:\Users\Giacomo\Documents\build-opennn-Desktop_Qt_5_8_0_MinGW_32bit-Debug\opennn\debug\libopennn.a(testing_analysis.o): In function `ZNK6OpenNN15TestingAnalysis19calculate_roc_curveERKNS_6MatrixIdEES4_':
C:\Users\Giacomo\Documents\build-opennn-Desktop_Qt_5_8_0_MinGW_32bit-Debug\opennn/../../OpenNN-master/opennn/testing_analysis.cpp:1425: undefined reference to `GOMP_parallel'

C:\Users\Giacomo\Documents\build-opennn-Desktop_Qt_5_8_0_MinGW_32bit-Debug\opennn\debug\libopennn.a(testing_analysis.o): In function `ZNK6OpenNN15TestingAnalysis20calculate_lift_chartERKNS_6MatrixIdEE._omp_fn.2':
C:\Users\Giacomo\Documents\build-opennn-Desktop_Qt_5_8_0_MinGW_32bit-Debug\opennn/../../OpenNN-master/opennn/testing_analysis.cpp:1958: undefined reference to `omp_get_num_threads'

I have seen the reported issue on windos 7 and I have added the code:

QMAKE_CXXFLAGS += -std=c++11 -fopenmp -pthread -lgomp
QMAKE_LFLAGS += -fopenmp -pthread -lgomp
LIBS += -fopenmp -pthread -lgomp 

unfortunatelly it does not work in my case and I get the same mistakes.

**Comment by RoberLopez** [comment]
We have updated the project and it should work fine.
