### ISSUE TITLE
dev branch: 

### ISSUE THREAD

**Issue by shleym2000** [Artelnics/opennn#289]
The FLT_MAX constant introduced in the https://github.com/Artelnics/opennn/blob/c11dd80e0095a91537690f895f4bc424236e4f1c/opennn/neurons_selection.h#L240 causes compiling error at least in Visual Studio, because it matches the existing Macros and it is being immediately substituted with the numeric value of that macro

Current line:

`int FLT_MAX=10; //alvaros
`
It should have a different name, for example THE_FLT_MAX.

`int THE_FLT_MAX=10; //alvaros
`
Or better yet, since it is a static constant, we'd better make it a "static const" like

`static const int THE_FLT_MAX=10; //alvaros
`

**Comment by rkuang9** [comment]
It seems they've stop working on this project. Check out https://github.com/rkuang9/flare
