### ISSUE TITLE
error at InformednessOptimizationThreshold

### ISSUE THREAD

**Issue by hocduong** [Artelnics/OpenNN#29]
Error	C2065	'MaximumIterations': undeclared identifier.
Error	C2065	'maximum_time': undeclared identifier.
Error	C2065	'performance_functional_pointer': undeclared identifier.

please check this error,

**Comment by RoberLopez** [comment]
The InformednessOptimizationThreshold class has been removed and that error has been eliminated. 

Thanks for you contribution.
