### ISSUE TITLE
InformednessOptimizationThreshold error

### ISSUE THREAD

**Issue by hocduong** [Artelnics/OpenNN#30]
class InformednessOptimizationThreshold 
Error	C2065	'MaximumIterations': undeclared identifier.
Error	C2065	'maximum_time': undeclared identifier.
Error	C2065	'performance_functional_pointer': undeclared identifier.

please check this error,

**Comment by shlublu** [comment]
Additionnally this couple of files seems unused. I just removed them from the repo when manually building the lib under MS Visual C++ and no build error occurred - I was not expecting that.

**Comment by RoberLopez** [comment]
Sorry about that. The problem has been fixed.
