### ISSUE TITLE
PerformanceFunctional

### ISSUE THREAD

**Issue by TrifonT** [Artelnics/OpenNN#38]
PerformanceFunctional type found in file informedness_optimization_threshold.cpp is not declared anywhere.

**Comment by BrainStone** [comment]
I'm having this issue too!

Both gcc and VisualStudio are complaining about this. Would a compilation log help?

**Comment by BrainStone** [comment]
Another thing I discovered is that file isn't even compiled when using cmake. So it could be deleted.

@TrifonT I'm assuming you also just set your build chain to compile all sources. You can savely ignore this file.

**Comment by TrifonT** [comment]
@BrainStone  thanks for comments and info. 
Anyway I quit trying using this project some time ago.

**Comment by RoberLopez** [comment]
Sorry about that. The problem is fixed now.
