### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by tex** [Artelnics/OpenNN#4]
msvobod :: ~/tmp/OpenNN ‹master*› » gcc --version                                                                                                                           2 ↵
gcc (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

msvobod :: ~/tmp/OpenNN ‹master*› » qmake                                                                                                                                   2 ↵
msvobod :: ~/tmp/OpenNN ‹master*› » make
cd tinyxml2/ && ( test -e Makefile || /usr/lib/qt/bin/qmake /home/milan/tmp/OpenNN/tinyxml2/tinyxml2.pro -o Makefile ) && make -f Makefile 
make[1]: Vstupuje se do adresáře „/home/milan/tmp/OpenNN/tinyxml2“
make[1]: Pro „first“ nebude nic uděláno.
make[1]: Opouští se adresář „/home/milan/tmp/OpenNN/tinyxml2“
cd opennn/ && ( test -e Makefile || /usr/lib/qt/bin/qmake /home/milan/tmp/OpenNN/opennn/opennn.pro -o Makefile ) && make -f Makefile 
make[1]: Vstupuje se do adresáře „/home/milan/tmp/OpenNN/opennn“
g++ -c -pipe -fopenmp -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -Wall -W -D_REENTRANT -DQT_NO_DEBUG -I. -I../tinyxml2 -Ieigen -I/usr/lib/qt/mkspecs/linux-g++ -o variables.o variables.cpp
In file included from variables.h:32:0,
                 from variables.cpp:16:
vector.h: In member function ‘OpenNN::Vector<long unsigned int> OpenNN::Vector<T>::sort_less_indices() const’:
vector.h:3611:15: error: ‘begin’ is not a member of ‘std’
     std::sort(std::begin(indices), std::end(indices), [this](size_t i1, size_t i2) {return (*this)[i1] < (*this)[i2];});
               ^
vector.h:3611:36: error: ‘end’ is not a member of ‘std’
     std::sort(std::begin(indices), std::end(indices), [this](size_t i1, size_t i2) {return (*this)[i1] < (*this)[i2];});
                                    ^
vector.h:3611:118: warning: lambda expressions only available with -std=c++11 or -std=gnu++11
     std::sort(std::begin(indices), std::end(indices), [this](size_t i1, size_t i2) {return (*this)[i1] < (*this)[i2];});
                                                                                                                      ^
vector.h: In member function ‘OpenNN::Vector<long unsigned int> OpenNN::Vector<T>::sort_greater_indices() const’:
vector.h:3633:15: error: ‘begin’ is not a member of ‘std’
     std::sort(std::begin(indices), std::end(indices), [this](size_t i1, size_t i2) {return (*this)[i1] > (*this)[i2];});
               ^
vector.h:3633:36: error: ‘end’ is not a member of ‘std’
     std::sort(std::begin(indices), std::end(indices), [this](size_t i1, size_t i2) {return (*this)[i1] > (*this)[i2];});
                                    ^
vector.h:3633:118: warning: lambda expressions only available with -std=c++11 or -std=gnu++11
     std::sort(std::begin(indices), std::end(indices), [this](size_t i1, size_t i2) {return (*this)[i1] > (*this)[i2];});
                                                                                                                      ^
Makefile:999: návod pro cíl „variables.o“ selhal
make[1]: *** [variables.o] Chyba 1
make[1]: Opouští se adresář „/home/milan/tmp/OpenNN/opennn“
Makefile:89: návod pro cíl „sub-opennn-make_first-ordered“ selhal
make: *** [sub-opennn-make_first-ordered] Chyba 2

**Comment by tex** [comment]
archlinux

**Comment by FernandoGomezP** [comment]
Added the flags for c++11 in unix systems and changed the std functions in the new update.
