### ISSUE TITLE
Can I use the network directly but not export to a expression file?

### ISSUE THREAD

**Issue by redsunschan** [Artelnics/OpenNN#42]
Currently I'm using this library for my Machine Learning AI school project, but I have to export the expression file, past to python and get the result back to the game. It's work but absolutely not efficient.
Is there any method that I can simply use the network like "predict()" function in sckit?

**Comment by RoberLopez** [comment]
If you want to use the neural network from C++, you can simply call the method calculate_outputs. 

If you want to use it from Python, you need to export the expression. 

Best regards
