### ISSUE TITLE
performance_term.h not found

### ISSUE THREAD

**Issue by MKesenheimer** [Artelnics/OpenNN#47]
The file performance_term.h was deleted in commit cf1736ce02ccad4d512b55011573848e5582b465, however the files final_solutions_error.h, independent_parameters_error.h, inverse_sum_squared_error.h, solutions_error.h rely on it.

**Comment by mad-b** [comment]
So, did anyone restored this file? Or, how to solve this issue?

**Comment by RoberLopez** [comment]
Sorry about that. The PerformanceTerm class was old, now the code has been refactored and it does not include it.
