### ISSUE TITLE
Check date-time methods in Vector and Matrix

### ISSUE THREAD

**Issue by RoberLopez** [Artelnics/OpenNN#66]
time_t and struct tm are confusing. Is it possible to use some std functions?

Some methods seem to add 1 day to the timestamp:

time[i] = mktime(&time_info) + 3600*24;

What is is wrong here?

**Comment by xinsuinizhuan** [comment]
your example airfoil_self_noise is not function. Because your split in vector.h is crash，your n is 1000，and this->size is 903，so vector is off.
