### ISSUE TITLE
example is not work, check your vector.h 

### ISSUE THREAD

**Issue by xinsuinizhuan** [Artelnics/OpenNN#67]
the example is not work  in the newest version,the spilt is crash in vector.h, beause the this->size is 903， but n is 1000, so the end_itr = std::next(this->cbegin(), k*n + n) is out of cross of vector.

**Comment by JavierSanchezB** [comment]
I just tested it and its working without problem.

Can you provide any extra information on how to reproduce the crash?
Thank you.

**Comment by RoberLopez** [comment]
Closed because no further information was given and the crash could not be reproduced.
