### ISSUE TITLE
incompatible to Embarcadero bcc?

### ISSUE THREAD

**Issue by Dediggefedde** [Artelnics/opennn#69]
First: Thanks for creating this project!

For some projects we use Embarcaderos C++ Builder.
We use a older compiler version (6.44), though.

When I tried to include OpenNN, it asked about `__attribute__((aligned(n)))`, which is probably `__attribute__((alloc_align(n)))` for the bcc32 compiler. Thus I added the define for this.

However, now it complains about a line in `/eigen/src/Core/util/Meta.h`: 
`template <class T, unsigned int Size> struct remove_const<const T[Size]> { typedef T type[Size]; };`
The number of parameter does not match redeclaration.

Can this be fixed quickly or is the eigen-library simply incompatible with the c++-builder?

**Comment by jandres-artelnics** [comment]
Hi @Dediggefedde , 

We use:
   1. Visual C++
   2. GCC
   3. Clang

We have not tried Embarcadero bcc.

If you find bugs please feel free to open a new issue. 

Thank you.
