### ISSUE TITLE
Build Issue for Visual Studio 2019 - cannot open file libopennn.a

### ISSUE THREAD

**Issue by dsm501** [Artelnics/opennn#73]
I have tried to build OpenNN using the instructions for Visual Studio at http://www.opennn.net/documentation/building_opennn.html#VisualStudio. 

I did all the necessary steps however when i try to build any of the examples i get the following error:  LNK1104 cannot open file '..\..\opennn\libopennn.a'	simple_function_regression	C:\OpenNN\OpenNN\build\examples\simple_function_regression\LINK	1	

I've had a look for that file libopennn.a and it is no where to be seen in my OpenNN repository at all. 

I am using Visual Studio 2019, any help on this matter would be great thanks.

**Comment by JavierSanchezB** [comment]
Make sure you have set the build type to *Release* and build opennn first (ricght click on it in the "solutions explorer" -> build). After that it should give no errors.
I have just checked, and the only time I got your error message was for not building opennn prior to the example.

Hope this helps.

**Comment by dsm501** [comment]
> Make sure you have set the build type to _Release_ and build opennn first (ricght click on it in the "solutions explorer" -> build). After that it should give no errors.
> I have just checked, and the only time I got your error message was for not building opennn prior to the example.
> 
> Hope this helps.

When i open an example such as simple_function_regression i simply open the simple_function_regression.vcxproj file and it opens in visual studio, i don't see opennn anywhere in the solutions explorer after opening it this way. Am i doing something wrong?

**Comment by JavierSanchezB** [comment]
You are not supossed to open each example individually.
Instead, open the `OpenNN/build/OpenNN.sln` file. This file includes the library, tests and all the examples.
