### ISSUE TITLE
Whether to consider support lstm method?

### ISSUE THREAD

**Issue by xinsuinizhuan** [Artelnics/OpenNN#75]
Lstm is the best method to forecast!

**Comment by GuillermoArtelnics** [comment]
Hello xinsuinizhuan.

At this moment, we have just uploaded a new version of `OpenNN`. In this new version the LSTM have been implemented.

I hope you find it useful.

**Comment by xinsuinizhuan** [comment]
Glad to this.Is there some example to use it? In example, i can't see example with lstm and recurrent?

**Comment by GuillermoArtelnics** [comment]
In the examples you can find the airline_passengers and temperature_forecasting, which include LSTM code for forecasting.
If you need more information about LSTM in `OpenNN`, you can see `long_short_term_memory_layer.cpp/.h`.
