### ISSUE TITLE
Undeclared Identifier: MaximumSelectionLossIncreases

### ISSUE THREAD

**Issue by error454** [Artelnics/opennn#76]
In trying to integrate OpenNN into another framework I've failed compiling with an undeclared identifier in [scaled_conjugate_gradiant.cpp:2014](https://github.com/Artelnics/OpenNN/blob/72498474ebd0a269bb1f258d902e92f4ab576070/opennn/scaled_conjugate_gradient.cpp#L2014):
`results_pointer->stopping_condition = MaximumSelectionLossIncreases;`

Looking at the `StoppingCondition` enum in [optimization_algorithm.h:73](https://github.com/Artelnics/OpenNN/blob/449b346f9438025e404bced7c7c84e4109f4845f/opennn/optimization_algorithm.h#L73) I see that indeed there is no definition:
```c++
enum StoppingCondition{MinimumParametersIncrementNorm, MinimumLossDecrease, LossGoal, GradientNormGoal,
                       MaximumSelectionErrorIncreases, MaximumIterationsNumber, MaximumTime};
```

I've added it to allow compilation to succeed but was concerned by its absence.

**Comment by shleym2000** [comment]
It is clearly a typo in the code. 
Change MaximumSelectionLossIncreases to MaximumSelectionErrorIncreases and it will compile.

**Comment by shleym2000** [comment]
To avoid deletion of already deleted memory and the crash during execution I also had to add explicit rvalue constructor and rvalue assignment operator into the training_strategy.h file:

> 		Results(Results&& r)
> 		{
> 			gradient_descent_results_pointer = r.gradient_descent_results_pointer;
> 			r.gradient_descent_results_pointer = nullptr;
> 			conjugate_gradient_results_pointer = r.conjugate_gradient_results_pointer;
> 			r.conjugate_gradient_results_pointer = nullptr;
> 			quasi_Newton_method_results_pointer = r.quasi_Newton_method_results_pointer;
> 			r.quasi_Newton_method_results_pointer = nullptr;
> 			Levenberg_Marquardt_algorithm_results_pointer = r.Levenberg_Marquardt_algorithm_results_pointer;
> 			r.Levenberg_Marquardt_algorithm_results_pointer = nullptr;
> 			stochastic_gradient_descent_results_pointer = r.stochastic_gradient_descent_results_pointer;
> 			r.stochastic_gradient_descent_results_pointer = nullptr;
> 			adaptive_moment_estimation_results_pointer = r.adaptive_moment_estimation_results_pointer;
> 			r.adaptive_moment_estimation_results_pointer = nullptr;
> 		}
> 
> 		Results &operator =(Results&& r)
> 		{
> 			gradient_descent_results_pointer = r.gradient_descent_results_pointer;
> 			r.gradient_descent_results_pointer = nullptr;
> 			conjugate_gradient_results_pointer = r.conjugate_gradient_results_pointer;
> 			r.conjugate_gradient_results_pointer = nullptr;
> 			quasi_Newton_method_results_pointer = r.quasi_Newton_method_results_pointer;
> 			r.quasi_Newton_method_results_pointer = nullptr;
> 			Levenberg_Marquardt_algorithm_results_pointer = r.Levenberg_Marquardt_algorithm_results_pointer;
> 			r.Levenberg_Marquardt_algorithm_results_pointer = nullptr;
> 			stochastic_gradient_descent_results_pointer = r.stochastic_gradient_descent_results_pointer;
> 			r.stochastic_gradient_descent_results_pointer = nullptr;
> 			adaptive_moment_estimation_results_pointer = r.adaptive_moment_estimation_results_pointer;
> 			r.adaptive_moment_estimation_results_pointer = nullptr;
> 			
> 			return *this;
> 		}
>
