### ISSUE TITLE
Won't build

### ISSUE THREAD

**Issue by ghost** [Artelnics/opennn#78]
I am trying to build OpenNN on Fedora. But I just get this message

[ 84%] Linking CXX executable tests
[ 84%] Built target tests
make: *** [Makefile:106: all] Error 2

I am not skilled with CMake to determine what the problem is. I installed tinyxml2, is there any other libraries it needs? 

I just did this
mkdir build
cd build
cmake ..

The strange thing is, that if I then go to the examples and compile them, they work fine. But the tests all segfault, and the test suite can not find vector data.

**Comment by algorithmLOGIC** [comment]
I was able to build with 3.1 from source forge on Windows. It will compile with Mingw and VC++. It did not put the MPI include and libraries into the solution it generated, but I added them manually and it works with MPI. For OpenMP, it requires /openmp for visual C++. You will have to edit the cmakelists.txt file. Neither MPI or OMP worked with MingW at this time.

**Comment by algorithmLOGIC** [comment]
I now was able to build on Linux using the 3.1 @ sourceforge. For MPI, I had to add -fpermissive switch. Everything works fine. Will be cool, if support for importing Keras files were added, this is the best library for non-GPU.
