### ISSUE TITLE
vector.h  fabs() is ambiguous

### ISSUE THREAD

**Issue by jsprenkle** [Artelnics/OpenNN#79]
In vector.h at about line 1633 the following line fails to compile:
if(fabs(maximum - minimum) <= tolerance)

The fabs() function has an ambiguous argument.
Compiler is MSVC2013_64bit,

Suggested fix:

  double diff = maximum - minimum;
  return fabs(diff) <= tolerance;

to replace this:

//  if(fabs(maximum - minimum) <= tolerance) {
//    return(true);
//  } else {
//    return(false);
//  }

**Comment by GuillermoArtelnics** [comment]
Hi jsprenkle ,

We have taken into consideration the proposed solutions, we thank you for your contribution.
