### ISSUE TITLE
Running logical operations - data not found

### ISSUE THREAD

**Issue by dendisuhubdy** [Artelnics/OpenNN#8]
C02QH2D7G8WM:workspace userone$ logical_operations /usr/data/
OpenNN. Logical Operations Application.
OpenNN Exception: DataSet class.
void load_data(void) method.
Cannot open data file: ../data/logical_operations.dat

**Comment by FernandoGomezP** [comment]
You have to copy the logical_operations.dat file(https://github.com/Artelnics/OpenNN/tree/master/examples/logical_operations/data) to the folder ../data relative to the executable or you can change the code to select another folder
