### ISSUE TITLE
examples/breast_cancer bug?

### ISSUE THREAD

**Issue by aarlt** [Artelnics/OpenNN#82]
I just wanted to play around with `OpenNN`. I just started to investigate the different examples that are provided by `OpenNN`. 

The example `example/breast_cancer` seem not to run correctly.

```
OpenNN. Breast Cancer Application.
Performing order selection with simulated annealing method...
Trial number: 1
breast_cancer(25584,0x10e7d0dc0) malloc: *** error for object 0x7f96f9601850: pointer being freed was not allocated
Training loss: 0.0609825
Selection error: 7731.32
breast_cancer(25584,0x10e7d0dc0) malloc: *** set a breakpoint in malloc_error_break to debug
Stopping condition: Minimum parameters increment norm


Process finished with exit code 6
```

What could be the problem here? I'm right now using `master` @ `449b346f9438025e404bced7c7c84e4109f4845f`

**Comment by aarlt** [comment]
```
OpenNN. Breast Cancer Application.
Performing order selection with simulated annealing method...
Training slope is greater than zero.
Trial number: 1
Training loss: 0.00938249
Selection error: 0.361991
Stopping condition:

[1]    27473 segmentation fault  ../../../build/examples/breast_cancer/breast_cancer
```

**Comment by aarlt** [comment]
What is the current state of `OpenNN`? Can it be used in a productive environment?

**Comment by GuillermoArtelnics** [comment]
Hello aarlt.

At this moment, we have just uploaded a new version of OpenNN, where all the bugs have been fixed and improved. This new more compact and dynamic version, allows the user a better experience for the development of projects. 

OpenNN is now active, with ten software developers working every day on improving the library.

Thanks for your interest.

Artelnics team.
