### ISSUE TITLE
warning: '/*' within block comment

### ISSUE THREAD

**Issue by yurivict** [Artelnics/OpenNN#84]
clang-8 prints these warnings:
```
/usr/ports/misc/opennn/work/OpenNN-0.1-86-g449b346/opennn/weighted_squared_error.cpp:783:1: warning: '/*' within block comment [-Wcomment]
/*
^
/usr/ports/misc/opennn/work/OpenNN-0.1-86-g449b346/opennn/weighted_squared_error.cpp:888:1: warning: '/*' within block comment [-Wcomment]
/*
^
```

**Comment by GuillermoArtelnics** [comment]
Hello yurivict.

At this moment, we have just uploaded a new version of OpenNN, where all the bugs have been fixed and improved. This new more compact and dynamic version, allows the user a better experience for the development of projects.

Many thanks for your help. 

Artelnics Team.
