### ISSUE TITLE
"dev" branch - tons of warnings in Visual Studio 2019

### ISSUE THREAD

**Issue by shleym2000** [Artelnics/OpenNN#95]
dev branch code produces thousands of warnings due to minor type mismatches **in almost each module.**
These warnings can be eliminated by more careful choice of local variables (often type _auto_ would be sufficient) or _static_cast_ to the needed type as a last resort. 
For example, when opennn/statistics.cpp is compiled, I see stream of 

> ...
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.h(189): message : see reference to class template instantiation 'Eigen::Tensor<type,1,0,Eigen::DenseIndex>' being compiled
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(274,47): warning C4244: '=': conversion from 'const __int64' to 'float', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(305,47): warning C4244: '=': conversion from 'const __int64' to 'float', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(596,33): warning C4244: 'initializing': conversion from 'double' to 'type', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(596,26): warning C4244: 'initializing': conversion from 'double' to 'const type', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(650,34): warning C4244: 'initializing': conversion from 'double' to 'type', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(650,26): warning C4244: 'initializing': conversion from 'double' to 'const type', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(823,32): warning C4244: 'return': conversion from 'double' to 'type', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(926,32): warning C4244: 'return': conversion from 'double' to 'type', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(946,74): warning C4244: 'return': conversion from 'double' to 'type', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(1139,44): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(1148,46): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(1241,50): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(1249,50): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(1746,55): warning C4244: 'initializing': conversion from 'double' to 'type', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(1746,36): warning C4244: 'initializing': conversion from 'double' to 'const type', possible loss of data
> 1>C:\MyProjects\RTS\Trial\TestLib\SandBox\OpenNN\opennn\statistics.cpp(1861,77): warning C4554: '|': check operator precedence for possible error; use parentheses to clarify precedence
> ...

**Comment by GuillermoArtelnics** [comment]
Hi,

With the new refactoring many warnings have appeared which we are fixing. 

Thank you for the solution.
