### ISSUE TITLE
"dev" branch : question about Logical Operations Example

### ISSUE THREAD

**Issue by shleym2000** [Artelnics/OpenNN#97]
I was able to make Logical Operation Example fully compilable and runnable in the "dev" branch. I chose it because it is very simple and because its results would be easy for 99.99% of programmers to evaluate. The results get produced and printed in the correct format, but values of neural_network.calculate_outputs() are bogus.
Results are bogus because there was only one iteration of training by QuasiNewtonMethod::perform_training() - hardly enough to learn the logical table.

**Are there some more complex steps to make this example producing correct results after training?**

Here is output of this example:

> OpenNN. Logical Operations Example.
> Training with quasi-Newton method...
> OpenNN Warning: Parameters norm is 4.31602e+08.
> OpenNN Warning: Gradient norm is 3.34318e+09.
> Epoch 0: Minimum parameters increment norm reached.
> Parameters increment norm: 0
> Parameters norm: 4.31602e+08
> Training error: 0
> Gradient norm: 3.34318e+09
> Training rate: 0
> X Y AND OR NAND NOR XOR XNOR
> 1 1
> X = 1 Y = 1
> 1 1  0.060232 0.0852956  0.145092  0.205724  0.276471  0.227186
> 1 0
> X = 1 Y = 0
> 1 0 0.0839409 0.0975047   0.15332  0.202254  0.259261   0.20372
> 0 1
> X = 0 Y = 1
> 0 1 0.0913943  0.112779  0.143992  0.179262  0.227779  0.244794
> 0 0
> X = 0 Y = 0
> 0 0 0.163983 0.141232 0.151808 0.164894 0.194116 0.183967
> 
> C:\temp/test.exe (process 19888) exited with code 0.

Here is slightly the version of example/logical_operations/main.cpp : main() function: 

```
int main(void)
{
    try
    {
        std::cout << "OpenNN. Logical Operations Example." << std::endl;

        srand(static_cast<unsigned>(time(nullptr)));

        // Data set

        DataSet data_set("../data/logical_operations.csv", ';', true);

        Eigen::Tensor<OpenNN::DataSet::VariableUse, 1> column_uses(data_set.get_columns_number());
        column_uses.setValues({ OpenNN::DataSet::Input, OpenNN::DataSet::Input, OpenNN::DataSet::Target, OpenNN::DataSet::Target, OpenNN::DataSet::Target, OpenNN::DataSet::Target, OpenNN::DataSet::Target, OpenNN::DataSet::Target });
        data_set.set_columns_uses(column_uses);

        const auto inputs_names = data_set.get_input_variables_names();
        const auto targets_names = data_set.get_target_variables_names();

        // Neural network

        Eigen::Tensor<Eigen::Index, 1> layers_counts(3);
        layers_counts.setValues({ 2, 6, 6 });
        OpenNN::NeuralNetwork neural_network(OpenNN::NeuralNetwork::Classification, layers_counts);

        neural_network.set_inputs_names(inputs_names);

        neural_network.set_outputs_names(targets_names);

        // Training strategy

        TrainingStrategy training_strategy(&neural_network, &data_set);

        training_strategy.perform_training();

        // Save results

        data_set.save("../data/data_set.xml");

        neural_network.save("../data/neural_network.xml");

        training_strategy.save("../data/training_strategy.xml");

        // Print results to screen

        Eigen::Tensor<float, 2> inputs(1, 2);
        Eigen::Tensor<float, 2> outputs(1, 6);

        std::cout << "X Y AND OR NAND NOR XOR XNOR" << std::endl;

        inputs(0, 0) = 1.0;
        inputs(0, 1) = 1.0;

        outputs = neural_network.calculate_outputs(inputs);

        std::cout << std::endl << "X = 1 Y = 1" << std::endl << inputs << " " << outputs << std::endl;

        inputs(0, 0) = 1.0;
        inputs(0, 1) = 0.0;

        outputs = neural_network.calculate_outputs(inputs);

        std::cout << std::endl << "X = 1 Y = 0" << std::endl << inputs << " " << outputs << std::endl;

        inputs(0, 0) = 0.0;
        inputs(0, 1) = 1.0;

        outputs = neural_network.calculate_outputs(inputs);

        std::cout << std::endl << "X = 0 Y = 1" << std::endl << inputs << " " << outputs << std::endl;

        inputs(0, 0) = 0.0;
        inputs(0, 1) = 0.0;

        outputs = neural_network.calculate_outputs(inputs);

        std::cout << std::endl << "X = 0 Y = 0" << std::endl << inputs << " " << outputs << std::endl;

        return 0;
    }
    catch(exception& e)
    {
        std::cerr << e.what() << std::endl;

        return 1;
    }
}

```

**Comment by shleym2000** [comment]
It would be great to make this simple example working. Correct logical operation results would increase the trust into library and it can also be used as regression test while you are making massive changes to this library.

**Comment by GuillermoArtelnics** [comment]
Right now we are working on the optimization algorithms. It is a good idea to check the algorithms using this simple example.

Thank you for your contributions.
